### ISSUE TITLE
won't load in ie9/ie10

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#100]
ie9  error
![ie9](https://cloud.githubusercontent.com/assets/5547275/11583524/0b1a1142-9a5b-11e5-98c9-20e6ff469c4c.png)

ie10 error
![ie10](https://cloud.githubusercontent.com/assets/5547275/11583528/1020e8dc-9a5b-11e5-8d66-86560a1f38ed.png)

ie11 funguje

**Comment by mmmaly** [comment]
![screen shot 2015-12-04 at 12 21 46](https://cloud.githubusercontent.com/assets/3857547/11588568/c757da58-9a81-11e5-8808-24878558911d.png)

hmm, "mne to ide" (IE 10)

**Comment by mmmaly** [comment]
ale zrejme to suvisi s tym, ze som zakazal vsetky nedoveryhodne protokoly.
related:
https://stackoverflow.com/questions/31438678/internet-explorer-10-this-page-cannot-be-displayed-when-loading-my-site

**Comment by martinmacko47** [comment]
Ja som skusal na W7 SP1. Plan s podporovanim browsrov som mal takyto:
IE8-: nepodporovane (a nefunguje, lebo standardne kniznice tu uz nefunguju)
IE9-10: gracefull degradation (moze vyzerat skaredo, ale malo by fungovat) 
IE11+: full support
Firefox/Chrome/Opera: Aktualna verzia minus 3
Safari: nemam prehlad vo verziach, testujem na Safari 7

Skus pogooglit, ako to riesia robia velke weby.

**Comment by martinmacko47** [comment]
Nejaky napad, co s tym? Ci na IE9 a IE10 na W7 sa vykasleme?

**Comment by mmmaly** [comment]
Nechcem uz povolovat TLS 1.0... v podstate tie browsery bez dalsieho patchovania maju byt zastarale. Mam vlastne aj problem najst pocitac s w7, aby som to otestoval.
Mozeme to zatial zavriet, ak by sa dakto stazoval, tak to doriesim.
