### ISSUE TITLE
uvodzovky sa zmrvia v maili na "&quot;"

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#101]
vo formulari pouzijem normalne uvodzovky, vysledok napr.

Dátumy a výsledky dopravných prieskumov, vykonaných v súvislosti s projektom &quot;Diaľnica D4, Rýchlostná cesta R7&quot; (prezentovaného v súčasnosti aj pod názvom &quot;obchvat Bratislavy&quot;).

**Comment by martinmacko47** [comment]
Malo by to byt fixnute. Pls otestuj na dev serveri. Otestuj aj savenut ako draft, loadnut a potom submitnut. Rovnako sa spravalo aj doplnenie ziadosti.

**Comment by martinmacko47** [comment]
Pls, skontroluj, ci to funguje a to pridam do deploy branch.

**Comment by mmmaly** [comment]
funguje

**Comment by martinmacko47** [comment]
Mergnute do deploy branche. Mozes nasadit.

**Comment by mmmaly** [comment]
nasadene
