### ISSUE TITLE
Text predmetu bez diakritiky

### ISSUE THREAD

**Issue by JakubKmet** [martinmacko47/chcemvediet#104]
Doplnit diakritiku do textu v poli Predmet pri podavani ziadosti

**Comment by martinmacko47** [comment]
@mmmaly pls na dev servri otestuj, ci Ti ziadost s makcenami v subjekte pride mailom spravne. Ci sa makcene nejak nepokazia.

**Comment by mmmaly** [comment]
ano, funguje.

**Comment by mmmaly** [comment]
@martinmacko47 je to uz v deploy?

**Comment by martinmacko47** [comment]
ano...
Branch: https://github.com/martinmacko47/chcemvediet/commits/deploy   
Commit: 3f028fd

**Comment by mmmaly** [comment]
ok, tym padom bolo pullnute. Napokon, uz to vidim aj na prod serveri, ze je to s makcenmi.
