### ISSUE TITLE
vysvetlit hviezdicky vo formularoch + povolit ziadosti bez predmetu

### ISSUE THREAD

**Issue by JakubKmet** [martinmacko47/chcemvediet#105]
Pri vyplnani ziadosti mame polia oznacene *. Absentuje jej vysvetlenie. Navrh na text je na drive doplneni v subore Nova ziadost

**Comment by martinmacko47** [comment]
Naozaj je ta vysvetlivka potrebna? Vacsinou aj tak mame skoro vsetky polia povinne. A ked uzivatel nieco nevyplni, tak system ho dodatocne upozorni, ze policko je povinne.

V projekte mame strasne velke mnozstvo formularov. Ak vysvetlivku uvedieme pri jednom formulari, potom by sme ju mali uviest pri vsetkych formularoch.

**Comment by JakubKmet** [comment]
Hviezdička nemusí byť, ale ešte by som otvoril tému povinné vypísanie
predmetu žiadosti. Aj kolegyňa váhala, čo tam dať a to už desiatky
infožiadostí naposielala. Čiže hviezdičku by som nechal tam, kde sa
rozhodneme, že nie všetky polia sú povinné.
ᐧ

2015-12-05 21:38 GMT+01:00 martinmacko47 <notifications@github.com>:

**Comment by mmmaly** [comment]
Som presvedceny, ze skrateny nazov - t.j. v tomto pripade zaroven sluzi aj ako predmet ziadosti, je velmi uzitocna vec. Pre ludi, co posielaju viacero ziadosti, je to mimoriadne prakticke.
Navyse sluzi aj ostatnym ludom pri vyhladavani, ktori vidia zhruba predmet ziadosti. A je jasne, ze pri vyhladavani sa tych ziadosti moze vyskytnut velmi vela. Je nepredstavitelne, ze by niekto mal potom rozklikavat kazdu jednu ziadost a citat si ju celu, ze ci ho zaujima.

**Comment by JakubKmet** [comment]
OK, veď uvidíme, ako to bude vyzerať v praxi a čo budú ľudia dávať do
predmetu. Ale to čo spomínaš by sa malo časom robiť nejakým systémom
kategorizácie nie?
ᐧ

2015-12-07 12:28 GMT+01:00 mmmaly <notifications@github.com>:

**Comment by martinmacko47** [comment]
Jakub, k novej teme, prosim Ta, vzdy otvor novy issue. Paradoxne z rovnakeho dovodu, preco aj pri ziadostiach je predmet, aby sa v issue dalo vyhladavat podla predmetu :-)

**Comment by mmmaly** [comment]
ad kategorizacia: To je nieco ine. Predstavujem si, ze po tom, ako urcime kategorie, bude kazda ziadost dodatocne, automaticky alebo poloautomaticky (ponukne tagy, clovek vyberie) este kategorizovana. Momentalne ich nechcem urcovat, lebo neviem, ako portal budu vyuzivat ludia, ale predstavujem si nieco take, ako: peniaze, zmluvy, korupcia, interne dokumenty, smernice, atd. Tu sa da odrazit od toho, ci odpoved od institucie je len jedna veta, alebo je prilozeny dokument, ci v dokumente su spominane cisla alebo nejake klucove slova ("EUR", "zmluva", "smernica", ...).

Vygenerovanie kratkeho popisu z dlheho je ovela tazsia uloha.

![screen shot 2015-12-07 at 12 25 25](https://cloud.githubusercontent.com/assets/3857547/11628321/36f065bc-9cf1-11e5-9b42-4d6c800ddcf4.png)

**Comment by martinmacko47** [comment]
Ale je pravda, ze vymysliet dobry predmet ziadosti moze byt pre cloveka komlikovane. Preto do manualu asi bude treba napisat clanok vysvetlujuci, preco predmet je dolezity a ako ho spravne pisat. Plus kopec uzitocnych prikladov pre inspiraciu.

Vytvoril som issue #113, kde mozeme spisovat zoznam tem, ktore netreba v manuale zabudnut pokryt.
