### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#108]

**Comment by lpk90901** [comment]
Ahojte, pridavam moje poznamky k dizajnu tejto podstranky, ktore sme si definovali minuly rok na jednom zo stretnuti [ak dobre chapem ze tato issue sa tyka zobrazovania vysledkov a dalsieho vyhladavania na celom portali]

Filtrovanie vysledkov vyhladavania [a la advanced search http://www.otvorenezmluvy.sk/documents/search]:

Hlavny search bar - kombinacia 2 funcii:
* klucove slova sa ukazuju ako “vymazatelne tagy x”, kym nestlacim enter
* Autocomplete - bude mi ukazovat existujuce kategorie/instituecie..

Zakladne filtrovanie: [v sidebare]
* moje ziadosti
* vsetky ziadosti
* institucie

Advanced filtrovanie: [v sidebare]
* kategorie [institucii - 20] a tie maju podkategorie
* lokalita [kraje - mestske casti - ]
* tagy [bude mi to navrhovat najcastejsie sa vyskytujuce tagy]

Spozob zobrazenia vysledkov:

* Pocet vysledkov
* Vysledok [odlisit zakladne typy vysledkov: *ziadost*, *institucia* ...]
   * Hlavny nazov
   * Uryvok textu zo ziadosti/popis institucie...
* Paginacia

**Comment by martinmacko47** [comment]
Implementovane pomocou google custom search v #209
