### ISSUE TITLE
New smail dispatcher

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#112]
Ked user klikne na linku, ze mu prisla nova posta, zobrazi sa mu stranka so zoznamom vsetkych jeho pending ziadosti. Zo zoznamu si vyberie ziadost, ku ktorej nova posta patri a po kliknuti na nu sa mu zobrazi wizard na uploadnutie novej posty.

Ak ma user nejake nezaradene emaily, zobrazi sa mu iba informacia o nich a linka, ze najprv ma zaradit emaily.

**Comment by martinmacko47** [comment]
Email dispatcher (#111) je vlastne specialnym pripadom smail dispatcher. Ak user nema ziadne nezaradene emaily, zobrazi sa mu zoznam jeho pending ziadosti, z ktoreho vyberie ziadost, ku ktorej nova posta patri. Ak user ma nezaradene emaily, automaticky ho to redirectne na prislusny wizard, kde email zaradi.

**Comment by martinmacko47** [comment]
Implementovane v branchi obligee_action_dispatcher. Treba otestovat, ze to robi to co ma:
 - [ ] Ak user nema ziadnu pending ziadost, nespravi to nic
 - [ ] Ak user ma len jednu pending ziadost, presmeruje ho to na wizard tejto ziadosti
 - [ ] Ak user ma nejake nove maily, presmeruje ho to na wizard niektorej jeho ziadosti s novymi mailami
 - [ ] Ak user nema ziadne nove maily a ma aspon dve pending ziadosti, necha ho vybrat, ku ktorej ziadosti chce postu pridat
 - [ ] Ake pripady som este zabudol?

**Comment by mmmaly** [comment]
setup.py in a brand new checkout fails with:

Server mode []: 1

Install requirements for unittesting? Y/N [N]: 

Installing requirements for the selected server mode:

$ env/bin/pip install -r requirements/base.txt -r requirements/local.txt

Downloading/unpacking Unidecode==0.04.17 (from -r requirements/base.txt (line 2))
  Could not find any downloads that satisfy the requirement Unidecode==0.04.17 (from -r requirements/base.txt (line 2))
Cleaning up...
No distributions at all found for Unidecode==0.04.17 (from -r requirements/base.txt (line 2))
Storing debug log for failure in /Users/mmm/.pip/pip.log
Traceback (most recent call last):
  File "setup.py", line 600, in <module>
    main()
  File "setup.py", line 570, in main
    install_requirements(configure)
  File "setup.py", line 274, in install_requirements
    [u'env/bin/pip', u'install'] + requirements);
  File "setup.py", line 37, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/pip', u'install', u'-r', u'requirements/base.txt', u'-r', u'requirements/local.txt']' returned non-zero exit status 1
Traceback (most recent call last):
  File "setup.py", line 600, in <module>
    main()
  File "setup.py", line 560, in main
    call(u'Rerunning with: env/bin/python', [u'env/bin/python', u'setup.py']);
  File "setup.py", line 37, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/python', u'setup.py']' returned non-zero exit status 1

**Comment by mmmaly** [comment]
skusam 
Unidecode>=0.04.17
ale nejde

**Comment by mmmaly** [comment]
(co je divne, lebo ostatne to maju tiez)
upgradoval som nieco u seba, ale mam 
$ python --version
Python 2.7.10

**Comment by mmmaly** [comment]
zvlastne, lebo 
$ pip install -r requirements/base.txt 
Downloading/unpacking Unidecode==0.04.17 (from -r requirements/base.txt (line 2))
  Downloading Unidecode-0.04.17.tar.gz (201kB): 201kB downloaded

**Comment by martinmacko47** [comment]
lebo nejaka sikulka prave odobrala Unidecode==0.04.17 z https://pypi.python.org/pypi/Unidecode  Takze to nebude fungovat uz v ziadnej vetve, ked zacnes s cistou instalaciou. Treba v requirements zmenit na Unidecode==0.04.18. Ak to zafunguje, tak rovno aj pushni zmenu.

Netusim preco niektori sikovnici maju stale potrebu mazat stare verzie z repozitara. Do requirements dat pausalne >= nemozeme, lebo nikdy nevies, ci nova verzia package nebude nekompatibilna/pokazena. Pri zmene verzie dependency treba pretestovat, ci vsetko ine ako ma. Pekna ukazka, preco sa snazim pouzivat co najmenej 3rd party kniznic.

Cim dalej tym mam vacsiu chut si spravit privatny pypi server, kde budu mirrory kniznic, ktore pouzivame.

**Comment by martinmacko47** [comment]
Tak beriem spat, package tam je: https://pypi.python.org/simple/unidecode/  Zrejme iba nejaky glitch. Skus este raz, mne to zbehlo.

**Comment by mmmaly** [comment]
ok, asi glitch, uz to stiahne v pohode, akurat ze znova haluzi:

Obligee dummy e-mail []: mail@{name}.example.com
Traceback (most recent call last):
  File "setup.py", line 600, in <module>
    main()
  File "setup.py", line 576, in main
    configure_cache(configure, settings)
  File "setup.py", line 366, in configure_cache
    default_prefix = slugify(configure.get(u'server_domain'))
  File "setup.py", line 25, in slugify
    s = unicode(s, u'utf-8')
TypeError: decoding Unicode is not supported
Traceback (most recent call last):
  File "setup.py", line 600, in <module>
    main()
  File "setup.py", line 560, in main
    call(u'Rerunning with: env/bin/python', [u'env/bin/python', u'setup.py']);
  File "setup.py", line 37, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/python', u'setup.py']' returned non-zero exit status 1

**Comment by mmmaly** [comment]
skusam docasne uzavriet do try-except bloku, vyzera, ze to funguje (aspon na ucely testovania).

Poznamka pre seba: Za closed sa ziadost oznaci na zaklade nejakeho cron jobu, nie v momente pridania (napriklad) full disclosure. T.j. toto treba pri testovani zobrat do uvahy.

- [x] Ak user nema nic, tak sa button ani nezobrazuje
- [x] Ak user ma len jednu ziadost, presmeruje ho to na wizard tejto ziadosti
- [x] Ak user ma len 1 uz  "uzavretu" ziadost (full disclosure), button sa nezobrazuje.
- [x] Ak nahodou nezbehol este cron (je "pending"), tak sa pridava k tejto ako haluz (nezaradenie odpovede), ok
- [x] Ak user ma 1 uz uzavretu ziadost (full disclosure), a 1 otvorenu, pridava k otvorenej
- [x]     Ak user ma aspon dve pending ziadosti, necha ho vybrat, ku ktorej ziadosti chce postu pridat

**Comment by mmmaly** [comment]
- [x] ak user ma mail, tak miesto buttonu je "Reagovat na email".

**Comment by mmmaly** [comment]
- [x] ak pocas pridavania pride mail, tak ten ziska prioritu a prepne sa to nanho

**Comment by mmmaly** [comment]
pri testovani sa mi objavila divna, asi nesuviaca chyba #129. Kedze to s tymto asi nesuvisi, tak toto mozeme povazovat za uzavrete a mergut.

**Comment by martinmacko47** [comment]
Ten "TypeError: decoding Unicode is not supported" by uz hadam mal byt fixnuty. Mergnute do vsetkych branchi.

Tie closed ziadosti vies testovat u seba lokalne pomocou timewarp.

**Comment by martinmacko47** [comment]
Pls, issue zavatvaraj, kym nie je zmena mergnuta a deploynuta, nech ju github neskryva. Ked vsetko funguje, tak zmen stav na "accepted", ja to potom mergnem do master. A ak nebudu ziadne netrivialne konflikty, tak to mergnem aj do deploy a dam do stavu "ready for deploy". Pls zatvaraj to az potom, ked to deplojneme.

**Comment by mmmaly** [comment]
ok. Ano, mozes mergnut.

**Comment by martinmacko47** [comment]
Mergnute, mozes deploynut. Pred deployom to pre istotu aspon trochu otestuj aj na testovacej kopii produkcneho servra.

Btw, pozor, v deploy branchi su uz vsetky tri branche.

**Comment by mmmaly** [comment]
Nasadil som to do testovacieho, ale hlasi mi:

   File "/var/www/test/chcemvediet/env/lib/python2.7/site-packages/django/core/cache/backends/memcached.py", line 163, in __init__
    import memcache
 ImportError: No module named memcache

spojene s: #62  #128

**Comment by martinmacko47** [comment]
Treba nainstalovat "python-memcached". V d1fcbdb som ho pridal do requirements, takze malo by to uz fungovat. Haluz vsak je, ze doteraz to nechybalo, kedze v tomto sa od 1. decembra nic nemenilo.

**Comment by mmmaly** [comment]
funguje, haluz. Ok, idem testovat.

**Comment by mmmaly** [comment]
nasadene na prod, #62 #128
