### ISSUE TITLE
Manual ako pouzivat portal

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#113]
Zoznam tem, ktore by mal manual pokryvat (prosim zoznam doplnujte):
- [ ] Ako napisat dobry predmet ziadosti + vela inspirativnych prikladov
- [ ] ...

**Comment by mmmaly** [comment]
Navrhujem dat tento text:
https://docs.google.com/document/d/1RvrLQqovp5kfwGxa8wu03L1zrhrSTVFFxZuvT4jTpa4/edit
do sekcie: https://www.chcemvediet.sk/sk/podavanie-ziadosti/

**Comment by martinmacko47** [comment]
> Navrhujem dat tento text:
> https://docs.google.com/document/d/1RvrLQqovp5kfwGxa8wu03L1zrhrSTVFFxZuvT4jTpa4/edit
> do sekcie: https://www.chcemvediet.sk/sk/podavanie-ziadosti/

Pridame v https://github.com/martinmacko47/chcemvediet/issues/335

**Comment by martinmacko47** [comment]
@mmmaly Text pridany. Mozeme task zavriet, ci este v ramci nieho si chcel nieco dalsie?

**Comment by martinmacko47** [comment]
@mmmaly ping
