### ISSUE TITLE
implement sitemap.xml

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#114]

**Comment by mmmaly** [comment]
vygenerovana  a zatial natvrdo pridana

**Comment by martinmacko47** [comment]
To som myslel ako issue pre seba niekedy do buducnosti aby som nezabudol, lebo to bude aj tak treba programovo generovat z databazy. Kludne mozeme mat zatial to, co si spravil, ale casom to prerobim. Takze zatial nezatvaram.

**Comment by mmmaly** [comment]
jasne, ok.

**Comment by martinmacko47** [comment]
Implementovane v  #208
