### ISSUE TITLE
UX: medzera predmet emailu

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#116]
![screen shot 2015-12-15 at 12 36 36](https://cloud.githubusercontent.com/assets/3857547/11809634/831d7406-a328-11e5-9ff1-182b3d461da0.png)

Do toho predmetu emailu dat medzi input a nazov napr. dvojbodku a medzeru.

**Comment by martinmacko47** [comment]
Medzi textom a input boxom je prave jedna medzera:
![predmet](https://cloud.githubusercontent.com/assets/5547275/12065049/dea07b8e-afd0-11e5-8d51-21b607e98737.png)
HTML:
![html](https://cloud.githubusercontent.com/assets/5547275/12065077/4c122028-afd1-11e5-9763-8be58d3fbb60.png)


Co tam je navyse je ten ramcek okolo inputboxu, ktory prekryva medzeru, a nemal by tam byt. Zislo by sa vediet aky presne browser na akom OS user ma.

**Comment by mmmaly** [comment]
o medzeru ani tak nejde, ale cloveku sa tam pyta nejaky oddelovac, a podla mna dvojbodka je dobry znak. Takto: 

Žiadosť o informácie podľa 211/2000 Z.z.: Predmet
Umozni to zacat vetu uplne nanovo, nielen priestorom ale aj znakom to oddeluje, a nebude to navadzat napriklad na pokracovanie vety ("Žiadosť o informácie podľa 211/2000 Z.z., o ktoré žiadali občania v roku 2015" -- z toho sa stane ", o ktoré žiadali občania v roku 2015", co je blbost).

**Comment by martinmacko47** [comment]
Aha jasne. Co je lepsie, dvojbodka alebo pomlcka?

**Comment by mmmaly** [comment]
imho dvojbodka, po nej sa pyta aj velke pismeno, aj v gramatike sa vravi, ze to vraj oddeluje vetu, zatial co pomlcka ma kadejake ine vyznamy.

**Comment by martinmacko47** [comment]
Ok, dam tam dvojbodku.

**Comment by martinmacko47** [comment]
V branchi ``inforequest_subject_field`` je pridana dvojbodka. Ale vyzera to kus divne, kedze pred dvojbodkou je bodka za z.

**Comment by martinmacko47** [comment]
Pls, pre istotu aj otestuj, ci som tu dvojbodku pridal na spravne miesto a bude aj po submitnuti v maily. Ak ma niekto teraz v drafte vlastnu dvojbodku alebo pomlcku, tak si to bude musiet pred submitom opravit sam.

**Comment by mmmaly** [comment]
![screen shot 2016-01-01 at 23 21 06](https://cloud.githubusercontent.com/assets/3857547/12072438/63358b56-b0de-11e5-8374-602c105d56f6.png)

Za mna ok.

**Comment by martinmacko47** [comment]
Ok. Mergnute do deploy. Nezabudni sa uistit, ze dvojbodka sa objavi aj v maili.

**Comment by mmmaly** [comment]
deployed #116 #117 #127
