### ISSUE TITLE
kodovanie odosielatela - zobrazuje sa rozsypany caj

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#117]
![screen shot 2015-12-15 at 12 39 59](https://cloud.githubusercontent.com/assets/3857547/11809697/fd25f124-a328-11e5-97d8-474cb45e94bc.png)

Neviem, ci  je to prepis podla RFC ale uzivatelovi asi lepsie zobrazit veci po slovensky.

**Comment by martinmacko47** [comment]
V DB budeme drzat nezakodovane mena a adresy odosielatelov a adresatov mailov. Mandrill vyzera, ze pri odosielanych mailoch ich zakoduje sam a pri dorucenych mailoch nam ich posle rozkodovane.

V branchi ``email_address_encoding`` som zmenil, ze pri generovani mailov sa mena a adresy odosielatelov a adresatov mailov nezakoduju a ulozia ako unicode stringy. Stare maily, co uz su v DB treba prekodovat migraciou, ktoru spusti setup.py

Treba pretestovat, ze:
 1. migracny skript prerobi zakodovane mena a adresy v tabulkach ``mail_message.from_name`` a ``mail_recipient.name`` na nezakodovane
  * tie co boli zakodovane prerobi na nezakodovane
  * tie co boli nezakodovane ostanu neporusene
 2. meno/email odosielatela mailu so ziadostou sa v DB **ne**zakoduje aj ked userovo meno obsahuje:
  * makcene/dlzne
  * somariny ako apostrofy/uvodzovky (aj nesparovane), zatvorky, <, >, zavinac, ciarku, ...
  * nieco, co vyzera ako email (napr. ak user ma meno ``Fero <somarina@haluz.com>``)
 3. meno/email adresata mailu so ziadostou sa v DB **ne**zakoduje aj ked nazov institucie obsahuje
  * makcene/dlzne
  * somariny ako apostrofy/uvodzovky (aj nesparovane), zatvorky, <, >, zavinac, ciarku, ...
  * nieco, co vyzera ako email
 4. odoslany email so ziadostou sa doruci a ked si pozries source doruceneho emailu, tak meno/email odosielatela/adresata je zakodovane ak obsahuje makcene/dlzne alebo haluze
 5. doruceny email s makcenami v mene odosielatela a adresata je spravne rozkodovany a do DB sa zapise rozkodovane mena a adresy odosielatela a adresata aj ked obsahuju makcene/dlzne alebo divne znaky

Treba este zistit, co sa stane ak (za predpokladu, ze je to mozne):
 1.  user zada email s makcenami pred zavinacom
 2.  user zada email s makcenami za zavinacom (skusit aj pre tld ktora podporuje IDN aj pre tld ktora IDN nepodporuje)
 3. institucia ma v DB email s makcenami pred zavinacom
 4. institucia ma v DB email s makcenami za zavinacom
 5. nam od institucie pride mail z adresy s makcenami pred zavinacom
 6. nam od institucie pride mail z adresy s makcenami za zavinacom

Ak nieco nedovoli zadat iba browser, tak skus to pretlacit na server, ci sa to nedovoli aj na servri.

**Comment by malymichal** [comment]
![screen shot 2016-01-01 at 22 05 44](https://cloud.githubusercontent.com/assets/6077493/12072188/daf09fd8-b0d3-11e5-89e5-cba0b6e6973e.png)


funguje (branch: email_address_encoding)

**Comment by mmmaly** [comment]
mozes dat do deploy.

**Comment by martinmacko47** [comment]
Mergnute, mozes deploynut. Pozor pri deploy, robi sa zasah do DB, takze skalopevne sa uisti, ze vsetko zafunguje. Naozaj prever vsetky body z https://github.com/martinmacko47/chcemvediet/issues/117#issuecomment-168084786

**Comment by mmmaly** [comment]
Hm, objavil sa este na testovacom: Ide o email 

 select from_name from mail_message where id=249; (testchcemvediet). Prosim Ta, skontrolujes, co sa tam mohlo stat? Pritom je to stale Michal Malý, len je ako =?utf-8?q?Michal_Mal=C3=BD?= .

![screen shot 2016-01-01 at 23 36 18](https://cloud.githubusercontent.com/assets/3857547/12072489/ab29828a-b0e0-11e5-9064-a02a41558ca5.png)

**Comment by mmmaly** [comment]
moj checklist:

- [x] migracny skript prerobi zakodovane mena a adresy v tabulkach mail_message.from_name a mail_recipient.name na nezakodovane
- [x] co bolo nezakodovane, ostane ok
- [x] meno/email odosielatela mailu so ziadostou sa v DB nezakoduje aj ked userovo meno obsahuje makcene/dlzne
- [ ] userovo meno obsahuje somariny
- [ ] userovo meno obsahuje email 
- [x] institucia ma makcene/dlzne
- [ ] institucia ma somariny
- [ ] institucia ma meno ako email
- [ ] doruci sa email
- [ ] doruceny email je spravne rozkodovany

- [ ] user ma email s makcenmi pred zavinacom
- [ ] user ma email s makcenmi za zavinacom
- [ ] institucia ma email s makcenmi pred zavinacom
- [ ] institucia ma email s makcenmi za zavinacom
- [ ] pride email s makcenmi pred zavinacom
- [ ] pride email s makcenmi za zavinacom

**Comment by mmmaly** [comment]
deployed #116 #117 #127

**Comment by martinmacko47** [comment]
Deploynute som teda zavrel. Body v https://github.com/martinmacko47/chcemvediet/issues/117#issuecomment-168349708 co nie su zaskrtnute si neskusal?
