### ISSUE TITLE
Button "preskúmať všetky žiadosti" 

### ISSUE THREAD

**Issue by JakubKmet** [martinmacko47/chcemvediet#122]
nefunguje vam tlacitko Preskumat vsetky ziadosti - feedback od Daniel Duris

![preskumat](https://cloud.githubusercontent.com/assets/16099873/11845186/f8a99fca-a412-11e5-9472-8b06d902084a.png)

**Comment by martinmacko47** [comment]
Najprv treba spravit #108

**Comment by martinmacko47** [comment]
Implementovane v  #210
