### ISSUE TITLE
Problem with a password

### ISSUE THREAD

**Issue by JakubKmet** [martinmacko47/chcemvediet#123]
pri prvej registrácii mi to hodilo chybovú hlášku (v prílohe). Po druhom pokuse (vypustil som z hesla znaky "?" a "," to prešlo. - napísal užívateľ Alexander Orros

[Err_msg.docx](https://github.com/martinmacko47/chcemvediet/files/65200/Err_msg.docx)

**Comment by martinmacko47** [comment]
Heslo na tu chuby nemalo vplyv. Heslo moze kludne obsahovat znaky ako otaznik a ciarka. @mmmaly pls pre istotu over na testovacej kopii produkcneho servra. Na dev servri to funguje.

Ako sa vsak dostal k chybovej hlaske, ktora je v prilohe je zahada. Ta chyba by sa mala zobrazit, iba ak niekto rucne upravil obsah html stranky. Co asi user nerobil. Teoreticky by takato chyba mohla nastat, ak sa userovi podarilo kliknut na prihlasenie presne v momente, ked sa redeployol server. @mmmaly pls skus take: 1. otvor login stranku, 2. restartni server (touch wsgi.py), 3. klikni na login.

**Comment by mmmaly** [comment]
skusil som na test-e, 1.,2.,3, a nic zvlastne sa nestalo, vsetko ako ma byt.

**Comment by mmmaly** [comment]
(dvakrat vsetko dobre, raz Zapamataj si ma, raz nezapamataj)

**Comment by martinmacko47** [comment]
Zatvaram. Ak sa chyba zopakuje, treba vytvorit novy issue a popisat podrobnejsie, co sa presne stalo.
