### ISSUE TITLE
Nezalomene riadky v html verzii emailu

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#125]
Mail ziadosti v plaintexte vyzera takto:
![a](https://cloud.githubusercontent.com/assets/5547275/11893935/5945057e-a574-11e5-85ef-dbf34a91e0f8.png)

V html verzii vsak takto (vid podciarknute):
![b](https://cloud.githubusercontent.com/assets/5547275/11893946/654c8c52-a574-11e5-846c-d7d6d2f0059d.png)

Mandrill zrejme to pochopil ako jeden odstavec a riadky spojil. Treba zistit, ako mandrillu povedat, aby riadky nespajal. Tj. aby namiesto konca riadku v html verzii doplnil &lt;br&gt;

**Comment by mmmaly** [comment]
vyzera, ze tuto riesia rovnaky problem https://stackoverflow.com/questions/29826425/mandrill-ignores-line-breaks-n
...a vyzera, ze to ide len cez html.

**Comment by mmmaly** [comment]
Este vyzera, ze dvojity enter nie je prevedeny na medzeru, co by mohol byt rychly fix.

**Comment by martinmacko47** [comment]
V branchi ``inforequest_email`` som dal dvojite entery. Nahodene na chv2.labs.

Treba oskusat, co s tym spravi Mandrill.
 - V uvode nad "Dobry den"
 - Na zaver za "Dakujem"

**Comment by malymichal** [comment]
ok, moze byt

**Comment by mmmaly** [comment]
mergnute bez konfliktov a deploynute spolu s #125 #144 #146 #149 #150 #154

**Comment by martinmacko47** [comment]
Obcas na prod servri daj ``git remote prune origin``, nech tam neostava kopec uz zmazanych branchi.
