### ISSUE TITLE
Zle zobrazenie prilohy

### ISSUE THREAD

**Issue by JakubKmet** [martinmacko47/chcemvediet#126]
Môže sa jednať a chybu zo strany povinnej osoby, ale pozrite sa na to, či to nie je náhodou našim systémom. Ziadost bola smerovaná na okresny urad v PN. 
![pn](https://cloud.githubusercontent.com/assets/16099873/11952795/8eff3688-a89b-11e5-9805-b84087cce6f9.png)

**Comment by martinmacko47** [comment]
Asi to bude suvisiet s touto chybou: #117

**Comment by martinmacko47** [comment]
V branchi ``attachment_name_encoding`` by to malo byt fixnute. Mergnut to mozeme az potom, ked sa mergne a nasadi #117, lebo sa menili rovnake casti kodu.

Treba otestovat, ze:
 - [ ] migracny skript prerobi zakodovane nazvy v tabulke ``attachments_attachment`` na nezakodovane a tie co boli nezakodovane nepokazi
 - [ ] ked odosleme email s prilohami s makcenami v nazve, tak sa do databazy ulozi nezakodovany nazov 
 - [ ] ked dostaneme (cez mandrill) email s prilohami s makcenami v nazve, tak sa do databazy ulozi nezakodovany nazov

To co vyzaduje posielanie mailov cez mandrill, mozes otestovat na chv2.labs. Branch je tam mergnuty.

**Comment by martinmacko47** [comment]
Aby sme si usetrili robotu, ak vsetko funguje tak ako ma, skus to rovno mergnut do ``master``. Ak sa mergne bez konfliktov, tak potom daj checkout ``deploy`` a do ``deploy`` mergni ``master``. Potom obe branche pushni a mozes to rovno deploynut.

Ak pri mergovani nastane konflikt alebo cokolvek nestandardne, tak nemerguj a nedeployuj. Konflikty poriesim radsej ja, nech viem o nich.

**Comment by mmmaly** [comment]
funguje.
mergnute bez konfliktov a deploynute.
