### ISSUE TITLE
Umoznit ulozit draft ziadosti, ak je v nom institucia bez emailu

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#127]
momentalne sa neda ulozit draft ziadosti, ak je v nom institucia bez emailu.  Da sa vsak ulozit napr. ziadost bez institucie uplne. Mozno takyto workaround by bol ok -- ak je v nom insitutcia bez emailu, tak sa ulozi bez institucie.

**Comment by martinmacko47** [comment]
Spravene c00b55c v branchi ``draft_to_obligee_without_email``

**Comment by mmmaly** [comment]
- [x] draft bez emailu ide ulozit
- [x] nepovoli poslat ziadost institucii bez emailu
- [x] nepovoli odoslat vyvolanu ulozenu ziadost, ak je institucia bez emailu
- [x] ide odoslat normalnu ziadost, ulozit normalny draft, odoslat normalny draft, a take klasicke veci.

cize funguje, prosim  draft_to_obligee_without_email - c00b55c dat do deploy.

**Comment by martinmacko47** [comment]
Mergnute, mozes deploynut

Pozor mergnute je viacero vetiev... Vzdy si prekontroluj https://github.com/martinmacko47/chcemvediet/network co je mergnute.

**Comment by mmmaly** [comment]
deployed #116 #117 #127
