### ISSUE TITLE
podrobnejsie chybove reporty

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#128]
Zisli by sa podrobnejsie chybove reporty. V branchi
"detailed-error-reports" je nastavene posielanie podrobnejsich reportov.
Ale je problem, ze tam je strasne vela informacii, ktore by asi nemali
ist nesifrovanym kanalom. Hlavne ked to prechadza cez kadejaky mandrill
a google. Sice hesla a podobne su vyhviezdickovane, ale aj tak.

Treba sa rozhodnut: Ci taketo reporty zapneme, alebo radsej nie?

**Comment by mmmaly** [comment]
som za zapnutie, ked uz nebudu chodit reporty od uzivatelov, mozeme casom vypnut. Ale minimalne do konca januara by som to zapol.

**Comment by martinmacko47** [comment]
Mergol som to do master aj do deploy. Pls, pred deployom to skus nejak otestovat, ze to aj posiela rozumne chybove reporty, ale sa Ti to bude blbo testovat, kedze pri testovani mas vypnute emaily. Jedine, co mozes pozriet je mail, co by sa odoslal, cez admin rozhranie.

**Comment by mmmaly** [comment]
nasadene na prod (#62  #112 #128)
