### ISSUE TITLE
indikacia nahravania suborov

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#130]
Urobit daku indikaciu, progress bar, ked sa subor(y) nahrava(ju).

Asi najjednoduchsie by bolo dat  bublinu suboru, ktora nemusi byt dynamicka s progress barom, len tam bude napisane nejake "Loading..." alebo daco take. A potom ked sa nahra, dat uz normalnu bublinu.

**Comment by martinmacko47** [comment]
Okrem toho treba aj nejak jasne dat najavo, ze upload sa dokoncil alebo zlyhal.

**Comment by martinmacko47** [comment]
V branchi ``attachment_upload_progress`` je spraveny pri uploadovani progressbar. Branch je mergnuna na chv2.labs. Ked sa subor uploaduje tak tlacitko upload je disablovane. Ak user chce uploadnut viac suborov, bud ich musi vybrat naraz, alebo musi pockat, kym sa uploadnu. Ked sa upload nepodari, vypise sa chyba.

Pri skusani to neskusaj na localhoste, lebo localhost je prilis rychly. Bud to prezen nejakym tunelom, alebo testuj na chv2.labs.

Otazku maximalnej velkosti prilohy nechavam na samostatny issue.

**Comment by martinmacko47** [comment]
Aby sme si usetrili robotu, ak vsetko funguje tak ako ma, skus to rovno mergnut do ``master``. Ak sa mergne bez konfliktov, tak potom daj checkout ``deploy`` a do ``deploy`` mergni ``master``. Potom obe branche pushni a mozes to rovno deploynut.

Ak pri mergovani nastane konflikt alebo cokolvek nestandardne, tak nemerguj a nedeployuj. Konflikty poriesim radsej ja, nech viem o nich.

**Comment by mmmaly** [comment]
Paci sa mi ta indikacia, pekne urobene.

**Comment by mmmaly** [comment]
spravil som oba merge, aj nasadil.

**Comment by martinmacko47** [comment]
Btw, mergoval si composite_field_outline do master alebo master do composite_field_outline? Lebo graf https://github.com/martinmacko47/chcemvediet/network je z toho nejak zmateny.
