### ISSUE TITLE
email bol poslany, ale ukazuje ho ako "zaradeny do fronty"

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#133]
![screen shot 2015-12-28 at 12 01 20](https://cloud.githubusercontent.com/assets/3857547/12017726/c8ed7d50-ad5a-11e5-9371-791b7452285f.png)

pritom v copy@chv.sk vidim, ze email (aspon teda  jeho bcc kopia) bol odoslany.

**Comment by martinmacko47** [comment]
Pls, prekontroluj este po niekolkych hodinach, ze stale pise, ze je zaradany do fronty. Ak ano, pls, napis sem aj jeho ID z DB.

**Comment by mmmaly** [comment]
ano, stale (po 4 hod od otvorenia ticketu).

Skontroloval som to este v Madrille v logu, tam svieti Delivered.

![screen shot 2015-12-28 at 16 13 26](https://cloud.githubusercontent.com/assets/3857547/12020553/ff970d1c-ad7d-11e5-85d5-bf605dcb5b6b.png)

ID v tabulke mail_message je 44.

**Comment by martinmacko47** [comment]
Nic prekvapive, ked nie je nastavene posielanie eventov z Mandrillu. Koli tomu nam ani nechodi info, ze mail bol doruceny, otvoreny a podobne.

V Mandrille: Settings / Webhooks / (vyber hook) / Edit a tam to vyzera takto:
![trigger-teraz](https://cloud.githubusercontent.com/assets/5547275/12067177/ba87a89c-aff5-11e5-93c7-fa0d811dc010.png)

Malo by to byt takto (urcite som Ti to pisal):
![trigger-spravne](https://cloud.githubusercontent.com/assets/5547275/12067180/c63f3ccc-aff5-11e5-95f7-34a12b5a0b20.png)


Btw, v Mandrille ku klucu pridaj nejaky comment, nech vieme, ze toto je produkcny kluc, keby vyrabame nejake dalsie niekedy.

**Comment by JakubKmet** [comment]
Naša stážistka má tiež dve žiadosti v tomto stave a vypršali lehoty. Odvolania teda podávať zatiaľ nebudeme.

**Comment by martinmacko47** [comment]
@mmmaly, mohol by si, prosim Ta, preverit v Mandrille, ci maily od stazistky odisli? Resp. co Mandrill hovori o ich doruceni. A pls, ponastavuj ten Mandrill, nech nam posiela eventy.

**Comment by mmmaly** [comment]
ano, pisal si. Je mozne, ze som to nastavil ale pri dalsej zmene kluca vymazal a znova nenastavil.
Teraz je nastaveny trigger vsetkom okrem Whitelist changes, Blacklist changes a recipient unsubscribes.

**Comment by mmmaly** [comment]
Stare ziadosti uz asi nebudu notifikovane, vsak?

**Comment by martinmacko47** [comment]
Pre stare uz asi nebude. Bude to treba opravit rucne/skriptom. Rozumny postup je asi pozriet v Mandrill logoch zoznam mailov, ktore neboli dorucene. Tie oznacit ako nedorucene rucne. A potom ostatne oznacit ako dorucene. Nic lepsie nevymyslime. Pozor, ak ma mail viacerych recipientov, tak jeden moze byt doruceny a jeden nedoruceny. Mandrill tusim logy uchovava len nejaku obmedzenu dobu.

**Comment by JakubKmet** [comment]
Prosím, trocha sa v tom strácam, odišli tie maily nakoniec alebo nie? máme
podávať odvolania?
ᐧ

2016-01-07 2:40 GMT+01:00 martinmacko47 <notifications@github.com>:

**Comment by mmmaly** [comment]
skontrolujem, za chvilu poslem mail.

**Comment by mmmaly** [comment]
HC: info.hc je korektny mail, doruceny bol, ale nebol precitany.
Porusenie zakona.
PN,SA,TT:  Prednostovia si emaily otvorili (vidim tam Outlook), ale
nic s tym neurobili.
BA,SC,RK: Mali sme stare maily, nedorucili sa, prosim preposlat,
ospravedlnujem sa stazistkam.

**Comment by malymichal** [comment]
stare maily fixnute nemame, ale povazujem to uz za bezpredmetne, kedze uz uplynulo dost casu. Kto co mal, bud mu odpovedali, alebo to vyhnilo.

**Comment by mmmaly** [comment]
Stare maily fixnute nemame, ale povazujem to uz za bezpredmetne, kedze uz uplynulo dost casu. Kto co mal, bud mu odpovedali, alebo to vyhnilo.
Inak vyzera, ze funguje.
