### ISSUE TITLE
wizard: 1.krok otazka -- doplnenie ziadosti -- preformulovat text

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#134]
Uzivatelovi sa stalo, ze v prvej otazke wizardu zvolil nespravnu moznost.
"Je odpoveď inštitúcie otázka? Pýta sa vás inštitúcia na niečo? "
(Pochopitelna) reakcia: Nepytaju -- ziadaju doplnenie. 
To ho zmiatlo, zvolil nie, vyzva na doplnenie sa teda zatriedila ako nieco uplne ine.

Preformulovat text na:

"Je odpoveď inštitúcie otázka, resp. výzva na doplnenie ziadosti? Vyžaduje od vás dodatočné informácie, aby mohla ďalej pokračovať v spracovávaní žiadosti? "

**Comment by martinmacko47** [comment]
Jakub, pls, premysli ako to napisat a zmenu zapis do googledocs. Potom to nahodim,

**Comment by JakubKmet** [comment]
ahojte, návrh nového textu je v google dokumentoch

**Comment by martinmacko47** [comment]
Zmena nahodena v branchi ``master`` aj na chv2.labs testovacom serveri.

Ked sa zmenil popis, netreba zmenit aj moznosti?

**Comment by JakubKmet** [comment]
ešte raz som prešiel text a zmenil som aj možnosti. Maťo nahoď to ešte raz. Vďaka

**Comment by martinmacko47** [comment]
nahodene aj so zmenenymi možnostami

**Comment by mmmaly** [comment]
je to ok.

![screen shot 2016-01-03 at 13 58 27](https://cloud.githubusercontent.com/assets/3857547/12078857/200bcdaa-b222-11e5-816e-9f0c5f547747.png)

**Comment by martinmacko47** [comment]
Mergnute do deploy.

**Comment by mmmaly** [comment]
nasadene.
