### ISSUE TITLE
Verifikovat domeny v mandrille a nastavit DKIM/SPF

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#135]
Preco su tam tie vykricniky a X-ka?

![verify-domains](https://cloud.githubusercontent.com/assets/5547275/12067216/7c37c5bc-aff6-11e5-8fb7-4c7d3af3207c.png)

**Comment by mmmaly** [comment]
aha, neuvedomil som si, ze treba aj pre @, spravil som len pre mail. Nastavene. 
O nejaky cas treba checknut
https://mandrillapp.com/settings/sending-domains

Mam este problem s verifikaciou domeny mail, ked neprijimame mail inde ako na mandrile. Uvidim, ako to bouncne.

**Comment by malymichal** [comment]
![screen shot 2016-01-25 at 16 35 14](https://cloud.githubusercontent.com/assets/6077493/12555488/badf4a12-c381-11e5-8650-38578830996c.png)

**Comment by malymichal** [comment]
![screen shot 2016-01-25 at 16 38 35](https://cloud.githubusercontent.com/assets/6077493/12555567/1c1ee60c-c382-11e5-9513-c25732191193.png)
ok nastastie som to videl v logoch.
