### ISSUE TITLE
Mandrill: nastavit aby sa adresati emailov videli navzajom

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#136]
V Mandrille: Settings / Sending Defaults / expose recipients
![expose-recipients](https://cloud.githubusercontent.com/assets/5547275/12067239/d9e0b700-aff6-11e5-8d16-351f24639b9b.png)

Treba asi zaskrtnut, nie? Ked ma institucia viacero mailov, resp. ak odpovedame na odpoved z institucie z ineho mailu, nez na aky sme poslali ziadosti, tak by asi bolo vhodne, aby sa adresati navzajom videli.

Po nastaveni by sa to zislo aj nejak pretestovat. Ale neviem ako.

**Comment by mmmaly** [comment]
Zapnute.

Na prod easy: dat ziadost napr. na minv, BCC pride na copy@ch. Zrovna dnes taky vidim - dva maily, kazdy separatne, takze sa nevidia.

Pre chv2 (ty mas na to kredence?), -- dakde k mojmu uradnickemu emailu pridat inu moju variantu mailu, a budem to vidiet. Ale prvy sposom imho staci.

![screen shot 2016-01-07 at 09 18 11](https://cloud.githubusercontent.com/assets/3857547/12165644/e433d826-b51f-11e5-82a5-ae2c2cffacdd.png)

**Comment by martinmacko47** [comment]
Na chv2 je "expose recipients" zapnute. Otestovat to mozes tak, ze cez admin nejakej institucii pridas viac testovacich emailov. Pri testovani radsej pouzi uplne rozne emaily, lebo gmail moze zdetekovat, ze Ti 2x prisiel rovnaky mail a spravit s tym nejaku magiu, co nechces.

Pozor, maily institucii, co zmenis v adminovi sa po kazdom spusteni ``setup.py`` na chv2 resetnu.

**Comment by mmmaly** [comment]
ano, otestovane na chv2, vidia sa.

**Comment by mmmaly** [comment]
medzitym uz aj na prod niekto posielal (Ruzinov), vidia sa aj tam.
