### ISSUE TITLE
Najbytocny ramcek okolo kompozitnych fieldov

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#138]
V #116 bol printscreen kompozitneho fieldu, v ktorom dielci field mal okolo seba ramcek. Ramcek by mal byt iba okolo celeho fieldu, nie okolo jeho komponent. Vieme v akom browri sa to tak zobrazuje?

Chybny vzhlad:
![](https://cloud.githubusercontent.com/assets/3857547/11809634/831d7406-a328-11e5-9ff1-182b3d461da0.png)

Spravny vzhlad:
![](https://cloud.githubusercontent.com/assets/5547275/12065049/dea07b8e-afd0-11e5-8d51-21b607e98737.png)

**Comment by mmmaly** [comment]
zistim. (Mozno mal Developer mod. )

**Comment by mmmaly** [comment]
za mna FF, Safari bez ramceku.

**Comment by martinmacko47** [comment]
Ja som skusal aktualny FF na linuxe, aktualny FF a Chrome na Win7, IE 10 a 11 na Win7 a Safari 7. Nikde ramcek nebol.

**Comment by mmmaly** [comment]
"Chrome ubuntu, spravi to ked ma ten input focus."

potvdrdzujem, Chrome Mac Version 47.0.2526.106 (64-bit) takisto, ked ma focus.

![screen shot 2016-01-01 at 23 41 06](https://cloud.githubusercontent.com/assets/3857547/12072498/3dc351fc-b0e1-11e5-95ee-54516cd36fab.png)

**Comment by mmmaly** [comment]
navrhujem neriesit, nevyzera to rusivo.

**Comment by martinmacko47** [comment]
ak to bude trivialne, fixnem, ak nie, tak necham tak

**Comment by martinmacko47** [comment]
V branchi ``composite_field_outline`` by to malo byt fixnute. Teda aspon v chrome.

**Comment by mmmaly** [comment]
funguje aj mne.

![screen shot 2016-01-03 at 14 02 29](https://cloud.githubusercontent.com/assets/3857547/12078866/ae9b74f8-b222-11e5-9faa-209a8b27279d.png)

**Comment by martinmacko47** [comment]
Mergnute do deploy.

**Comment by mmmaly** [comment]
nasadene.

**Comment by martinmacko47** [comment]
Ok. Zatvaram.

Btw, mergoval si ``composite_field_outline`` do ``master`` alebo ``master`` do ``composite_field_outline``? Lebo graf https://github.com/martinmacko47/chcemvediet/network je z toho nejak zmateny.
