### ISSUE TITLE
URL in notification email is wrong

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#14]
We received a new e-mail regarding your inforequest to ....

To read the e-mail and decide what it is, go to
http://127.0.0.1:8000/en/inforequests/detail/2/#decide

Should reflect the real address of the server instead of 127.0.01.

**Comment by mmmaly** [comment]
so far I have tried server name "localhost". This is the url produced: http://www.localhost/en/inforequests/detail/1/#decide
Notice www. It could probably cause problems with some arrangements, which do not use www.

**Comment by martinmacko47** [comment]
You need to rerun ``setup.py`` and input Server domain correctly (real domain with or without www / localhost / IP).
