### ISSUE TITLE
Neverejne trackovanie issues 

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#140]
Obcas sa nam v issues vyskytuju veci, ktore mozno by nemuseli byt verejne. Napriklad mena userov. Casom sa mozno podari omylom tu zavesit aj nejake vaznejsie veci, ktore by sa nemuseli zverejnovat. Bohuzial github nevie mat privatne issues (ak nie je privatny repozitar). Nejaky napad, kde trackovat issues? Najlepsie zadarmo? Teoreticky mozeme nainstalovat aj privatnu Bugzillu, ale to je asi zbytocne overkill.

**Comment by JakubKmet** [comment]
nestačil by nám nejaký spreadsheet?
ᐧ

2016-01-02 13:09 GMT+01:00 martinmacko47 <notifications@github.com>:

**Comment by mmmaly** [comment]
ja si platim na druhom konte kvoli nejakym veciam privatne repo. Mozem zriadit novy repozitar, v ktorom nebude nic, len issues, a pridat vas ako kolaborantov.

**Comment by martinmacko47** [comment]
Mozeme pouzit, ale privatne issues maju zase taky problem, ze ich nikto okrem collaboratorov nemoze pridavat. Takze user nam neverejnu issue neprida. Bugzilla ma zaklikavatko pre kazdu issue, ci je verejna.

Zatial by som na bezne issues pouzival bezne issues s tym, nech si kazdy dava pozor, aby do issues nepisal veci, co by nemali byt verejne. A ked bude treba nieco neverejne, tak spravime tam, ako pises.

Anyway, nepaci sa mi minat $ na blbosti, ked nemame $.

**Comment by mmmaly** [comment]
ok, tym padom zatvaram, ak by sa vyskytlo nieco, tak otvorte (alebo dajte ako issue do privatneho repo).
