### ISSUE TITLE
Maximalna velkost prilohy a maximalny pocet priloh.

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#141]
Aku povolime maximalnu velkost prilohy k ziadosti a inym akciam usera? Aktualne sa stabilne uploaduju 1MB prilohy. Analogicky, aky maximalny pocet a maximalny sucet velkosti priloh povolime k jednej ziadosti? Ako prvy krok, treba zistit, ake obmedzenia ma Mandrill.

Zrejme niekde do helpu k upload tlacitku treba napisat, ake su obmedzenia.

Tato issue sa netyka priloh, ktore nam pridu emailom od institucie. Pri nich asi obmedzenia nemaju zmysel. Ale co ak nam niekto posle nejaku extremne velku prilohu?

**Comment by martinmacko47** [comment]
Najprv treba dotiahnut #130

**Comment by mmmaly** [comment]
indikacia je pekna, tak som testoval, aka prejde. Na prod mi nepresla napr. ani 130KB priloha, na chv2 mi preslo nieco pod 1MB.

**Comment by martinmacko47** [comment]
Ten referer je rovnaky problem ako s formularmi. Django pri kazdom POST requeste kontroluje referera. Tusim som Ti niekde posielal aj analyzu, preco to tak robia.

Ako teda s obmedzeniami velkosti a poctu priloh? Resp. celkovej velkosti vsetkych priloh dokopy? Aj vzhladom na Mandrill, ze co cez neho prejde.

**Comment by mmmaly** [comment]
cez Madrill v pohode preslo to co je na chv2, cize 1MB, aj viacnasobne prilohy, 
Na prod som este velku prilohu v ziadosti neprikladal, tak nemam otestovane. 

Ale pisu, ze 25MB total message size: https://mandrill.zendesk.com/hc/en-us/articles/205582407-Does-Mandrill-Support-Attachments-

**Comment by martinmacko47** [comment]
Cize prilohy obmedzime kazdu na 15MB a v sucte tiez na 15MB. A v pocte na nejakych 20? Btw, niektore prilohy sa nemusia encodovat ako base64, ale aj ako Quoted-printable, ktore je niekedy efektivnejsie, ale niekedy nie. Neviem ako to Mandrill robi.

Obmedzenia bude treba napisat do niekam do helpu k formularu. A tiez bude treba implementovat aj clientsize kontrolu velkosti, nech user zbytocne neuploaduje 5 minut 100MB subor, a potom dostane chybu.

**Comment by martinmacko47** [comment]
Cize prilohy obmedzime kazdu na 15MB a v sucte tiez na 15MB. A v pocte na nejakych 20? Btw, niektore prilohy sa nemusia encodovat ako base64, ale aj ako Quoted-printable, ktore je niekedy efektivnejsie, ale niekedy nie. Neviem ako to Mandrill robi.

Obmedzenia bude treba napisat do niekam do helpu k formularu. A tiez bude treba implementovat aj clientsize kontrolu velkosti, nech user zbytocne neuploaduje 5 minut 100MB subor, a potom dostane chybu.

**Comment by mmmaly** [comment]
ok, dajme tak.

Na serveri:

- [ ] pocet priloh max 20
- [ ] velkost 1 prilohy max 15 MB - @mmmaly
- [ ] velkost priloh spolu max 15 MB.

na clientside:
- [ ] pocet priloh max 20
- [ ] velkost 1 prilohy max 15 MB
- [ ] velkost priloh spolu max 15 MB.

**Comment by martinmacko47** [comment]
Kontrola na serveri:
 - pocet priloh max 20
 - velkost prilohy max 15MB (aj ak by sa podarilo dostat cez apache limit, tak to overi aj django; nekontroluje sa to vsak pri uploadovani, ale pri odosielani formulara)
 - velkost priloh spolu max 15MB

Kontrola na klientovi:
 - Na jeden klik sa daju uploadnut iba subory, ktore spolu nepresahuju 15MB
 - Na viacero klikov sa daju nahrat aj subory, ktore spolu presahuju 15MB alebo je ich viac ako 20. Pred submitnutim ma user moznost uploadnute subory premazat. Pre poriadnu kontrolu upload fieldu na clientovi by bolo treba spravit plnohodnotne validovanie formulara na clientovi, co zatial nejdem robit. Mozeme pridat ako issue do dalekej buducnosti.

Texty:
 - Pridal som k upload fieldu strucny help
 - Pridal som chybove hlasky, ked user prilozil vela suborov, alebo velke subory
 - Zoznam textov som spisal do googledocs a @JakubKmet ich ucese

Velkost a pocet priloh som obmedzil iba pri podavani ziadosti a posielani institucii doplnenie ziadosti. Ostava otvorene, ci pocet a velkost priloh treba obmedzit aj pri pridavani doslej klasickej posty od institucie? Na jednej strane, treba dat userovi moznost uploadnut vsetko, co prislo, ale na druhej strane, nech nam tam neuploadne autobus.

**Comment by mmmaly** [comment]
S tym autobusom si zatial nerobme starosti. Pri klasickej poste by som okrem toho nechal radsej vacsi limit, lebo kvalitny sken moze zaberat vela.

**Comment by martinmacko47** [comment]
Apach hard limit 15MB na jeden upload plati aj tak, takze ani pri uploadovani klasickej posty sa neda nahrat viac nez 15MB subor. Bolo by treba robit finty ako upload viacerymi requestami, co teraz nejdem robit. V takom pripade nech user nahra prilohy po strane. Hadam jedna strana nebude mat viac ako 15 MB.

Ak si skontroloval, ze vsetky body hore funguje, mozes issue zavriet.

Texty ma Jakub pripisane do google doc, tak casom ich snad dorobi.
