### ISSUE TITLE
nejde zmazat draft

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#142]
po kliknuti na x v prehlade rozpisanych ziadosti a odkliknuti potvrdzovacieho dialogu sa zobrazi (na prod)
 (pekna ) 404 stranka, v logu: `django.request WARNING Not Found: /sk/infoziadosti/zmazat-draft/5/X`

na chv2 sa zobrazi podrobnejsi 404 dump, kedze mame zapnuty debug.

**Comment by martinmacko47** [comment]
Fixnute v branchi ``delete_draft``. Ak ide, rovno mergni, najprv do ``master``, potom do ``deploy``. Pls merguj **do** ``master`` a nie naopak, nech graf branchi nechaosi.

**Comment by mmmaly** [comment]
funguje.

**Comment by mmmaly** [comment]
mergnute (checkout master, merge delete_draft, checkout deploy, merge delete_draft), 
deploynute.

**Comment by martinmacko47** [comment]
Btw, ako sa Ti podarilo, ze ``deploy`` nie je "prefixom" ``master``?
https://github.com/martinmacko47/chcemvediet/network

Aha uz vidim...
nie "checkout master, merge delete_draft, checkout deploy, merge ~~delete_draft~~"
ale "checkout master, merge delete_draft, checkout deploy, merge __master__"

Deploy by mal byt podmnozinou master. Tj. ze master je buduce deploy. Ked budes mat dve rozne vetvy, tak nebudes mat v deploy nutne to iste, co v master a teda sa bude testovat nieco ine. Merge z master do deploy by mat byt vzdy iba fast forward.

Mergni naspat ``deploy`` __do__ ``master``.

**Comment by mmmaly** [comment]
ok, mergnute deploy do master.
