### ISSUE TITLE
Privacy - Ochrana osobných údajov - vytvorit staticku podstranku

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#144]
- [x] skonvertovat dokument [Informacia_a_suhlas_dotknutej_osoby_track_150825_sk.docx](https://docs.google.com/document/d/1zhBE-ax4sARfXyQ7j6guQunAGMrAvJC0v6rQjMnSBvY/edit#) na html
- [x] dat ho ako staticku stranku s nazvom "Ochrana osobných údajov" do footra hned vedla "Podmienky používania"
- [x] nalinkovat tuto stranku v bode 10.3. [Podmienok použivania](https://www.chcemvediet.sk/sk/podmienky-pouzivania/)

**Comment by mmmaly** [comment]
pripajam txt dokument, @martinmacko47 , pls ak mas este ten skript na rozumnu konverziu do html, pouzi ten. 
[Informacia_a_suhlas_dotknutej_osoby_track_150825_sk.txt](https://github.com/martinmacko47/chcemvediet/files/79732/Informacia_a_suhlas_dotknutej_osoby_track_150825_sk.txt)

**Comment by martinmacko47** [comment]
Spravene v branchi ``ochrana_osobnych_udajov`` a nasadene na chv2.labs.

issues:
 - Hlavicku by sa asi zislo naformatovat, nech vyzera nejak rozumne. Bud nacrtni ako, alebo to zedituj priamo v ``/media/pages/sk/ochrana-osobnych-udajov/page.html``. Ak nieco zeditujes, tak pred deployom mi to daj este pozriet.
 - Hlaska "pristupnej tu" v bode 10.3 v podmienkach, kde je linka na tuto stranku, je divna.
 - Aj na tejto stranke aj na stranke s podmienkami su odkazy na odseky, nemali byt to byt naozaj odkazy?
 - Na mobile sa linky vo footri nezobrazovali. To bolo asi zle. Teraz sa zobrazuju, ale ked je display uzky, tak vyzeraju divne.

**Comment by mmmaly** [comment]
Hlaska -- mas pravdu, zapisujem si aj formatovanie a prelinkovanie.

Toto nasadme, a tieto kozmeticke veci v #54
