### ISSUE TITLE
Zobrazit viac institucii vo fielde pri podavani ziadosti

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#146]
Tak 50 institucii a pridat scrollbar. Otestovat, ako to bude vyzerat na mobile.

Vyplynulo diskusie pri #145

**Comment by lpk90901** [comment]
Ahoj Martin, 
pozrela som ako to riesia iny na UX forach.
[Autocomple + long dropdown on mobile]

Tu je sumar moznosti [zavisi co sa nam da implementovat]:

1] **CHOOSE ANOTHER**
Autocomplete ukaze len napr. prvych 5 top hits a link na dalsie moznosti, ktore sa objavia v popupe 
![choose-another](https://cloud.githubusercontent.com/assets/6820342/12196514/69b2eeda-b5ff-11e5-8af6-1d776e16357c.jpg)

2] **MOBILE SCROLL** [na mobile, v pripade ze na desktope pouzijeme scrollbar]
na dlhe zoznamy pouzit na mobilny scroll [nie som si ista ci to funguje v kombinacii s Autocomplete-om]
![native-mobile-scroll](https://cloud.githubusercontent.com/assets/6820342/12196558/aac49568-b5ff-11e5-81d7-f3e4017df05e.png)

3] **MULTIPLE SELECT**
V pripade, ze by sme vedeli hladat viacero klucovych slov - napr. "Bratislava", "urad"...
http://harvesthq.github.io/chosen/#selected-and-disabled-support

Dalo by sa nieco z toho pouzit?

**Comment by martinmacko47** [comment]
Spravene v brachi ``obligee_autocomplete``a nasadene na chv2.labs. Pri niektorych mestach ani 50 nalezov nestaci, ale zobrazit vsetky nalezy nemozeme, lebo ked user napise nieco strasne vseobecne, tak mu najde aj 1000 nalezov. Casom bude potrebne spravit rozumne AI na vyhladavanie. Zatial takto.

@lpk90901 zatial co najjednoduchsie, co sa da implementovat pomocou https://jqueryui.com/autocomplete/  Ked budeme mat to vyhladavanie poriadne premyslene, mozeme potom skusat nejake coolovejsie autocomplete kniznice.

**Comment by mmmaly** [comment]
ok, zatial takto

**Comment by martinmacko47** [comment]
Takze toto zatvaram, komplikovanejsie riesenie budeme riesit v #145
