### ISSUE TITLE
Chybajuce linky na clanky [homepage - blog widget]

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#147]
Rozdiely vo vybavovaní infožiadostí sú veľké
https://dennikn.sk/blog/rozdiely-vo-vybavovani-infoziadosti-su-velke/

Je možnosť požiadať o informácie dostupná naozaj pre každého?
https://dennikn.sk/blog/je-moznost-poziadat-o-informacie-dostupna-naozaj-pre-kazdeho/

**Comment by martinmacko47** [comment]
K linkam na blogy @JakubKmet prekontrololuje/upravi/doplni aj nadpis a perex. Ma to v zozname textov v google docs v "texts / X. Statické stránky" bod X1.f).2.

**Comment by martinmacko47** [comment]
Linky doplnime v #325
