### ISSUE TITLE
2x chybajuci text "Vedeli ste?"

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#148]
Ahoj Jakub, snazila som sa najst povodne citaty, ktore sme chceli pouzit, ale nepodarilo sa mi to. Chybaju nam 2 "Vedeli ste?" citaty na homepage > widget v spodnej casti. Mozes prosim poslat Martinovi nejake 2 zaujimave fakty?

**Comment by martinmacko47** [comment]
@lpk90901 V google docs pozri texts / X. Statické stránky a tam X1.f).3. Zatial tam @mmmaly nieco doplnil. Este ich @JakubKmet prekontroluje a dame ich na web.

**Comment by lpk90901** [comment]
Super, nemohla som to najst.

Navrhujem pouzit:
... podľa zákona na ziskanie informácií nepotrebujete uviesť dôvod, prečo ich potrebujete? 
... na podanie infožiadosti nepotrebujete formulár?
... slovenský infozákon má jedny z najkratších lehôt na odpoveď?

Share nefunguje - ale to asi viete?

**Comment by martinmacko47** [comment]
Ak tam este tie texty nie su, tak ich tam dopln. Ak uz tam su, tak pouzijeme vsetky, co tam su. Len ich musi este @JakubKmet textovo zrevidovat.

Ano, fb a twitter buttony pod tymi hlaskami este nefunguju.

**Comment by martinmacko47** [comment]
Navrhnute texty do sekcie "Vedeli ste?" doplnime v ramci #324

**Comment by martinmacko47** [comment]
Doplnene v ramci #324
