### ISSUE TITLE
Upozornenie, ze nieco nie je este implementovane

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#149]
Po kliknuti na linky a buttony, ktore este nie su implementovane by sa zisiel nejaky popup, ze toto este nie je implementovane. Aby ludia nereportovali, co este nie je a vieme, ze nie je.

**Comment by martinmacko47** [comment]
Spravene v branchi ``not_implemented`` a nahodene na chv2.labs. Len jednoduchy alert s jednoduchym textom, nech sa ludia necuduju, ze sa nic nedeje.

Alert sa zobrazi tu:
 - searchbox v headri
 - velky searchbox na hlavnej stranke
 - podporte nas na hlavnej stranke pod nadpisom _Prečo sa zaregistrovať?_
 - chcem prispiet na hlavnej stranke pod nadpisom _Financovanie_
 - linky na blogy na hlavnej stranke
 - tweet a share buttony na hlavnej stranke pod nadpisom _Vedeli ste?_
 - chcem prispiet vo footri
 - button archiv vsetkych ziadosti v zozname mojich ziadosti

Na co som este zabudol? Kde mame linky, buttony, nieco co nerobi nic a malo by?

**Comment by lpk90901** [comment]
@martinmacko47  ja som nic okrem spominanych neobjavila.

**Comment by JakubKmet** [comment]
Návrh textu: *Na vývoji tejto časti portálu pracujeme. Ďakujeme za
trpezlivosť.*
ᐧ

**Comment by martinmacko47** [comment]
Text upraveny. V branchi ``not_implemented`` a nahodene na chv2.labs.

**Comment by JakubKmet** [comment]
Skontrolované a je to ok. V ostrej prevádzke sa tiež vo vyskakovcom okne
bude objavovať url adresa portálu?
ᐧ

**Comment by mmmaly** [comment]
tiez som ok, 
" Áno, odpoveď nejako súvisí, chcem, aby mi admin pomohol identifikovať odpoveď inštitúcie." -> mometalne co robi? Mne sa vidi, ze nic (zatial). To je este asi vec, na ktoru upozornit.

![screen shot 2016-01-17 at 09 12 10](https://cloud.githubusercontent.com/assets/3857547/12376552/711a83de-bcfa-11e5-9396-975a9c0aa0a7.png)

**Comment by mmmaly** [comment]
toto zavrime a na email som otvoril #155.
