### ISSUE TITLE
Button Citajte viac gives 404 

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#15]
in SK version, button to learn more Citajte viac is not working and produces 404 error

Page not found (404)
Request Method: 	GET
Request URL: 	http://www.chcemvediet2.labs.poleno.sk/sk/o-projekte/

Using the URLconf defined in chcemvediet.urls, Django tried these URL patterns, in this order:

    ^media/(?P<path>.*)$
    ^static\/(?P<path>.*)$
    ^sitemap[.]xml$
    ^mandrill/
    ^sk/ ^$ [name='index']
    ^sk/ ^about/ [name='about']
    ^sk/ ^obligees/
    ^sk/ ^inforequests/
    ^sk/ ^accounts/
    ^sk/ ^accounts/
    ^sk/ ^admin/
    ^sk/ ^admin_tools/
    ^sk/ ^i18n/

The current URL, sk/o-projekte/, didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by martinmacko47** [comment]
@mmmaly pls review it and close it.

**Comment by mmmaly** [comment]
works, closing
