### ISSUE TITLE
Zmenit 1.landing page po prihlaseni na "Moje ziadosti"

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#150]
Momentalne to cloveka hodi na jeho profil.
Ci uzivatel uz ziadost podale alebo nie, prva stranka po prihlaseni by mala byt https://www.chcemvediet.sk/sk/infoziadosti/

**Comment by martinmacko47** [comment]
Spravene vo vetve ``page_after_login`` a nahodene na chv2.labs. @mmmaly pls checkni a deployni na prod.
