### ISSUE TITLE
Text "O čom to je?" na homepage

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#153]

**Comment by lpk90901** [comment]
@mmmaly @martinmacko47 chcete mat vsetko ten text co je v casti "O čom to je?" na homepage?

Lebo ak ano, tak by som to skusila vyriesit inak - takto to vyzera dost disproporcne..

**Comment by martinmacko47** [comment]
Nie, plan je, aby @JakubKmet napisal text zhruba takej vysky ako su ostatne stlpce. Zvysok sa presunie do about alebo inej podstranky a tam sa da iba linka.

**Comment by JakubKmet** [comment]
Viete mi prosím dať nejaký rozsah v počte znakov, do ktorého by som sa mal
zmestiť? Aby to korešpondovalo s vizuálom stránky. Myslím tým aj dolnú a
hornú hranicu. Vďaka.
ᐧ

2016-01-08 21:58 GMT+01:00 martinmacko47 <notifications@github.com>:

**Comment by lpk90901** [comment]
@JakubKmet napr. max 120 znakov?

**Comment by martinmacko47** [comment]
120 znakov to je tak 2 a pol riadka pri aktualnom fonte. Nie trochu malo? Ja by som skor povedal tak 600, max 800 znakov. Zhruba v dlzke ako su teraz prve dva odstavce.

**Comment by lpk90901** [comment]
120 SLOV, pardon!

**Comment by JakubKmet** [comment]
OK, ďakujem za mantinely :)
ᐧ

**Comment by martinmacko47** [comment]
Asi lepsie bude text "O čom to je?" na homepage nechat tak ako je a do prazdneho priestoru zobrazit tabulku cca 5-10 najnovsich zverejnenych ziadosti.

![home](https://user-images.githubusercontent.com/5547275/98144807-d9b9ed80-1eca-11eb-9f64-ad987d9650f5.png)

**Comment by martinmacko47** [comment]
Vyriesene v ramci #336. Do prazdneho priestoru sa pridali case studies a jednotlive bloky s obsahom sa preusporiadali.
