### ISSUE TITLE
Skryt login/signup pre prihlaseneho usera

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#154]
- v stlpcoch na hlavnej stranke
 - v menu (to by malo fungovat, ale treba pretestovat)
 - ked user zada rucne url ``/accounts/login/`` alebo ``/accounts/signup/`` tak by ho to malo niekam redirektnut (to by tiez malo fungovat, ale treba pretestovat)
 - kde este usera vyzivame k prihlaseniu?

**Comment by martinmacko47** [comment]
V branchi ``homepage_for_authenticated`` je text vyzyvajuci na login na hlavnej stranke pre prihlaseneho usera skryty. Je to nasadene na chv2.labs.

Treba este checknut body popisane vyssie a ci niekde inde neostali vyzvy na login.

**Comment by mmmaly** [comment]
funguje, a uz asi nie su ine miesta.
