### ISSUE TITLE
spytovaci email adminovi - ziadost o help

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#155]
![screen shot 2016-01-17 at 09 12 10](https://cloud.githubusercontent.com/assets/3857547/12376555/a9d896c0-bcfa-11e5-9f79-93d0671b02cb.png)

Po kliknuti dokoncit sa to tvari ako ok, ale tusim sa nic neposle.

**Comment by mmmaly** [comment]
navrh: poslat na info@chcemvediet.sk aspon nejaky note, idealne aj (link na) prilohu

**Comment by martinmacko47** [comment]
Idealne by sa zislo mat #59, aby sa to dalo sledovat, ale zatial asi len ten mail.

**Comment by martinmacko47** [comment]
Spravene v branchi ``master``.

Pri deployovani treba spustit ``python setup.py`` a nastavit ``SUPPORT_EMAIL``.

Treba otestovat:
 - Help v NotCategorized kroku wizardu; Postup: nova ziadost / zaradit odpoved od institucie / not a question / not a confirmation / not on topic
 - Help v InvalidReversion kroku wizardu; Postup: ziadost s odvolanim / is a decision / contains no info / was accepted / was not returned
 - Ze support request mail sa odosle ak user poziada o help
 - Ze support request mail sa neodosle ak user nepoziada o help
 - Vyskusat pripad, ked user zaradzuje e-mail
 - Vyskusat pripad, ked user zaradzuje klasicku postu
 - Prilohy, ktore user rucne uploadne sa prilozia k support request mailu
 - Prilohy, ktore prisli emailom od institucie sa neprilozia k support request mailu, ale support request mail obsahuje linku do admin rozhrania, kde sa daju pozriet

Problemy:
 - E-mail od institucie sa po poslani support requestu zaradi ako ``UNKNOWN``, takze user moze pokracovat v zaradzovani
    dalsich mailov k tej istej ziadosti. To neviem ci je spravne, ci by sme ho nemali nutit pockat,
    kym admin neodpovie. Taktiez tym, ze sa mail od institucie oznaci ako rozhodnuty, tak sa k nemu
    user uz nedostane. Preto ho bude musiet spravne zaradit admin, alebo ho vratit naspat
    zo stavu ``UNKNOWN`` na ``UNDECIDED``. Na to malo sluzit admin rozhranie, ktore este nie je. Takze to bude musiet admin rucne spravit cez django admin.
 - Tak ako pri kazdom doklikani wizardu do konca, hodnoty ulozene v rozklikanom wizarde (tj.
    v drafte wizardu) sa zmazu. To asi nie je dobre, pretoze ked admin userovi odpovie, tak user
    bude musiet vsetko vyklikat nanovo. Nezmazat draft wizardu vsak nemozeme, pretoze po zaradeni mailu od institucie do stavu ``UNKNOWN`` moze user otvorit wizard s dalsim mailom k tej istej ziadosti, kde by vsak mal predvyplnene hodnoty z predosleho mailu.

**Comment by mmmaly** [comment]
- [x] Help v NotCategorized kroku wizardu; Postup: nova ziadost / zaradit odpoved od institucie / not a question / not a confirmation / not on topic
- [ ] Help v InvalidReversion kroku wizardu; Postup: ziadost s odvolanim / is a decision / contains no info / was accepted / was not returned
- [ ] Ze support request mail sa odosle ak user poziada o help
- [ ] Ze support request mail sa neodosle ak user nepoziada o help
- [ ] Vyskusat pripad, ked user zaradzuje e-mail
- [x] Vyskusat pripad, ked user zaradzuje klasicku postu
- [x] Prilohy, ktore user rucne uploadne sa prilozia k support request mailu (na localhoste vyzera ok: ` attachments: [<Attachment: 180>]`)
- [ ] Prilohy, ktore prisli emailom od institucie sa neprilozia k support request mailu, ale support request mail obsahuje linku do admin rozhrania, kde sa daju pozriet

**Comment by mmmaly** [comment]
jednu vec som si neuvedomil, a to, ze pri postupovanej ziadosti moze byt clovek "blokovany" tym, ze nevie, kto mu vec poslal. 
Ale toto teraz neriesme ,kedze postupenych ziadosti je o dost menej, najjednoduchsie riesenie je momentalne pridat nejaku poznamku, ze: Vyberte hocico, ak neviete, a neskor poziadate o admina, ktory to spravne zatriedi.

![screen shot 2016-02-06 at 19 03 10](https://cloud.githubusercontent.com/assets/3857547/12868334/6565ea50-cd04-11e5-9036-7bb72956b845.png)

**Comment by mmmaly** [comment]
>     E-mail od institucie sa po poslani support requestu zaradi ako UNKNOWN, takze user moze pokracovat v zaradzovani dalsich mailov k tej istej ziadosti. To neviem ci je spravne, ci by sme ho nemali nutit pockat, kym admin neodpovie. Taktiez tym, ze sa mail od institucie oznaci ako rozhodnuty, tak sa k nemu user uz nedostane. Preto ho bude musiet spravne zaradit admin, alebo ho vratit naspat zo stavu UNKNOWN na UNDECIDED. Na to malo sluzit admin rozhranie, ktore este nie je. Takze to bude musiet admin rucne spravit cez django admin.

Tiez neviem, ci mu dat moznost pridavat, alebo ho nutit. Pockajme na realne pripady a uvidime, co bude lepsie riesenie. Moze sa stat, ze sa vacsina problemov "vyriesi" sama, cize user si to vo vlastnej rezii neskor popridava a admin len skontroluje. Je ale mozne, ze user to bude velmi bantovat, a admin to bude potom musiet cele napravat, vtedy by sme zvolili "blokujucu" verziu. Alebo nieco ine. Neblokujuca verzia ma tiez vyhodu, ze user tam moze ponahravat veci, ktore, hoci aj su zle, uz budu zverejnene, a teda budu sluzit ostatnym (i ked budu somrat, ze je to zle kategorizovane).

>     Tak ako pri kazdom doklikani wizardu do konca, hodnoty ulozene v rozklikanom wizarde (tj. v drafte wizardu) sa zmazu. To asi nie je dobre, pretoze ked admin userovi odpovie, tak user bude musiet vsetko vyklikat nanovo. Nezmazat draft wizardu vsak nemozeme, pretoze po zaradeni mailu od institucie do stavu UNKNOWN moze user otvorit wizard s dalsim mailom k tej istej ziadosti, kde by vsak mal predvyplnene hodnoty z predosleho mailu.

Hej, asi logicke, neda sa mat oboje.

**Comment by mmmaly** [comment]
Funguje, aj poslanie z prod, aj s prilohou.

**Comment by martinmacko47** [comment]
> jednu vec som si neuvedomil, a to, ze pri postupovanej ziadosti moze byt clovek "blokovany" tym, ze nevie, kto mu vec poslal. Ale toto teraz neriesme ,kedze postupenych ziadosti je o dost menej, najjednoduchsie riesenie je momentalne pridat nejaku poznamku, ze: Vyberte hocico, ak neviete, a neskor poziadate o admina, ktory to spravne zatriedi.

Treba niekde napisat vseobecny text, ze ked si nevedia rady, nech napisu mail adminovi.

> Tiez neviem, ci mu dat moznost pridavat, alebo ho nutit. Pockajme na realne pripady a uvidime, co bude lepsie riesenie. Moze sa stat, ze sa vacsina problemov "vyriesi" sama, cize user si to vo vlastnej rezii neskor popridava a admin len skontroluje.

User teraz sam nevyriesi nic. Akonahle dojde na koniec wizardu a posle help request, tak mail od institucie sa oznaci ako vybeveny a viac ho user nevidi. Takze ak sa na to admin vykasle, mail od institucie sa z pohladu usera strati.
