### ISSUE TITLE
krok https://www.chcemvediet.sk/sk/infoziadosti/obnova-promenady-v-casti-pri-pko-55/prisla-posta/5/ - institucia nenajdena

### ISSUE THREAD

**Issue by nekromoff** [martinmacko47/chcemvediet#156]
ale dalej ma to nepusti, lebo institucia v realite existuje, vo vasej DB nie, neexistuje vsak moznost zadat takuto instituciu, cize sa neviem dalej dostat na potvrdenie a som zaseknuty.

konkretne v DB nie je starz.sk

**Comment by mmmaly** [comment]
Doplnim. Na takuto vyznamnu instituciu som zabudol! ;)

**Comment by mmmaly** [comment]
(casom urobime notifikaciu adminom, ze treba doplnit instituciu)

**Comment by nekromoff** [comment]
ano, to by bolo najlepsie, nieco ako "nenasli ste, napiste nam udaje" - a
nasledne by to uzivatela pustilo proces dokoncit s tym, ze by sa vytvorila
nova (neschvalena) entita, ktorej by sa uz ale posta priradila

**Comment by mmmaly** [comment]
Starz vytvoreny.
