### ISSUE TITLE
wizard: Just join with previous event

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#160]
Vyzera, ze nejake problemy, reportovane uzivatelmi, by sa doriesili tlacidlom (resp. odpovedou na otazku vo wizardovi) "Toto co prislo, je len pokracovanie toho predchadzajuceho".
Tyka sa to najma priloh, ktore su nasekane kvoli priloham alebo kvoli tomu, ze odosielatel urobil chybu v prikladani prilohy a poslal znova. 
Zatial by som toto bral ako hypotezu/navrh, uvidime, ci sa takych pripadov bude mnozit a ci to nieco ine nepokryje lepsie.

**Comment by martinmacko47** [comment]
@mmmaly Toto by malo byt vyriesene s https://github.com/martinmacko47/chcemvediet/issues/172 (Opakujuce sa akcie institucie). Zataram.
