### ISSUE TITLE
Nesmie byt starsi ako 1 mesiac, nesmie byt novsi ako datum dorucenia.

### ISSUE THREAD

**Issue by nekromoff** [martinmacko47/chcemvediet#165]
Neriesitelna situacia - starsi email z 19.6. nie je mozne uz spracovat:

![obrazok](https://user-images.githubusercontent.com/8550349/30558036-771affb0-9cb0-11e7-8130-b9a3ef76058e.png)

![obrazok](https://user-images.githubusercontent.com/8550349/30558051-8102cdaa-9cb0-11e7-91be-74043db7eb9f.png)

**Comment by martinmacko47** [comment]
@mmmaly Fixnutim  #167 by toto malo byt vyriesene, ci? Pls prever. Ak ano, zatvor. Ak nie popis co este nefunguje.

**Comment by mmmaly** [comment]
funguje
