### ISSUE TITLE
Financovanie - zmenit CTA link na /podporte-nas

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#169]
CTA link "Chcem prispiet", ktory mal povodne smerovat na DAKUJEME stale nesmeruje nikam = mohli by sme tam dat link na PODPORTE NAS?

![cta-link](https://user-images.githubusercontent.com/6820342/37863789-41008e58-2f64-11e8-9eeb-4d1190876be1.png)

**Comment by martinmacko47** [comment]
Teraz to neviem fixnut, pretoze stranka "PODPORTE NAS" vobec v gite nie je. @mmmaly ju len dohackoval na servri. @mmmaly, pls commitni vsetko, co si robil na servri lokalne do PR, mergneme to a potom mozeme nieco fixovat.

**Comment by mmmaly** [comment]
dal som do branche support-us.
S jednou vecou som si nevedel dat rady v subore funding.html:
Toto funguje:
<a class="btn chv-btn-blue" href="/podporte-nas/">{% trans 'main:homepage:funding:donate' %}</a>
Po spravnosti ale v href by malo byt cosi ako {% page "/podporte-nas/" %} , co mi zial nefungovalo na tomto mieste, hoci inde funguje.

**Comment by mmmaly** [comment]
dal som do branche support-us.

**Comment by mmmaly** [comment]
Aha, este sa mi tam nepodarilo dat widget. Zatial je to citatelne a dava zmysel aj bez neho.

**Comment by martinmacko47** [comment]
@mmmaly 

K `page`: Prikaz treba includnut, ak ho chces pouzit. Rovnako treba `page` pouzit aj ked sa na pagi linkuju ine page, alebo subory v ramci page. Vid commit, v ktorom to opravujem: c6ebbdb8

K widgetu: Aky widget kde? Pls do samostatneho issue popis aky presne widget tam chces dat.
