### ISSUE TITLE
Schema pre normalizovanu verziu attachmentu

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#173]
### Django app `anonymization`

V `chcemvediet/apps/` vytvorit novu app `anonymization` a pridat ju do `INSTALLED_APPS` v `chcemvediet/settings/common.py`.

Pozri si Django dokumentaciu, co musi nova app obsahovat. Ale ak si spravne pamatam, tak by mal stacit prazdny `__init__.py`.

### Model pre normalizovanu verziu attachmentu

Vo vytvorenej app `anonymization` sprav model `AttachmentNormalization`. Inspiruj sa modelom `Attachment`. Novy model bude mat fieldy:
- `attachment`: FK na `Attachment`. NOT NULL.
- `successful`: boolean oznacujuci, ci normalizacia sa podarila. NOT NULL.
- `file`: Ako v `Attachment`, ale moze byt NULL ak normalizacia bola neuspesna alebo po normalizacii nevznikol ziaden subor. Uklada sa do adresara `attachment_normalizations`. 
- `name`: Ako v `Attachment`. NOT NULL. Doplni sa automaticky v `save` na zaklade `attachment.name` a noveho `content_type`
- `content_type`: Ako v `Attachment`, ale moze byt NULL. V `save` sa nedopocitava, ale musi sa explicitne nastavit pri normalizovani suboru. Hodnota pre `content_type` moze byt uvedena dokonca aj ak normalizacia zlyhala. V takom pripade hodnota reprezentuje aky typ suboru by vznikol, keby normalizacia bola uspesna.
- `created`: Ako v `Attachment`. NOT NULL.
- `size`: Ako v `Attachment`, ale moze byt NULL ak `file` je NULL
- `debug`: Lubovolny text, bude obsahovat debug vystup z normalizacie. NOT NULL, ale moze byt prazdny.

Sprav metody/properties `content`, `save` a `__unicode__` analogicky ako pri `Attachment`. Metodu `clone` (zatial) netreba. V `save` pri vytvarani novej instancie automaticky dopocitaj `file.name`, `created` a `size` analogicky ako pri `Attachment`. Field `name` tiez dopocitaj automaticky tak, ze zoberies `attachment.name` a zmenis mu priponu podla noveho `content_type`. Field `content_type` sa nedopocitava. Pozor, pri vytvarani novej instancie moze byt `file` neuvedene, v takom pripade `size` nechaj NULL.

Ku `AttachmentNormalization` sprav `AttachmentNormalizationQuerySet` analogicky ako pri ostatnych modeloch. Zatial iba s `order_by_pk` metodou. A pouzi to ako manager pre `objects`.

K fieldom pridaj komentare a `help_text` analogicky ako pri `Attachment`. Spomen tam, co sa automaticky dopocita v `save` a podobne. Pod fieldy pridaj komentare, ake backward relacie model pridava do inych modelov, a ake ma indexy. Vid komentare pri inych modeloch.

### Migracia

Sprav migraciu, ktora model `AttachmentNormalization` vytvori v DB. Vid migracie pre ine modely.

### Datachecks

Analogicky ako pri `Attachment` sprav `datachecks` funkciu, ktora skontroluje, ci vsetky `AttachmentNormalization`, ktore maju `file` not NULL, maju existujuci subor. A naopak, ci vsetky subory v adresari `attachment_normalizations` maju svoj `AttachmentNormalization`.

Predpokladam, ze vela kodu z `datachecks` pre `Attachment` reusnes. Ten reusnuty kod vydel do pomocnej funkcie, ktoru pouzijes na oboch miestach. Pomocnu funkciu daj napriklad do `poleno/attachments/utils.js`. Nezabudni datacheck zaregistrovat pomocou dekoratora `@datacheck.register`. A over, ze pri spusteni datachecks sa novy datacheck vykona a funguje (najde nezrovnalosti). Datachecks sa pustaju pomocou `env/bin/python manage.py datacheck`.

### Admin rozhranie

Analogicky ako pri `Attachment` sprav `admin.py`, kde nakonfigurujes admin obrazovku pre `AttachmentNormalization`. V `list_display` zobraz vsetky fieldy okrem `debug`. V `list_filter` umozni filtrovat rovnako ako vo `Attachment` akurat navyse aj podla `successful`. V `search_fields` umozni searchovat aj podla `debug`. K zobrazeniu `file` budes potrebovat spravit `download` view analogicky ako pri `Attachment`.

### Dokumentacia

V adresari `/misc` sprav subor `anonymization.odt`, kde popises dokumentaciu noveho modelu a jeho relaciu ku `Attachment`. Analogicky ako je v subore `attachments.odt` resp. ostatnych.

**Comment by viliambalaz** [comment]
Subor `poleno/attachments/utils.js` neexistuje. Mam vytvorit novy? A preco ma mat subor koncovku `.js`?

**Comment by martinmacko47** [comment]
> Subor `poleno/attachments/utils.js` neexistuje. Mam vytvorit novy? A preco ma mat subor koncovku `.js`?

`utils.py` samozrejme. A ano, ak neexistuje, tak ho vytvor.
