### ISSUE TITLE
Normalizacia priloh cez libreoffice

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#180]
**Depends on: #181**

V #181 sme spravili cron job, ktory normalizuje prilohy na pdf. Teraz pridame podporu pre konverziu pomocou libreoffice.

Cron job uprav tak, ze ak `Attachment.content_type` je podporovany libreoffice, tak prilohu skusime znormalizovat libreofficom. Zoznam `content_type` podporovanych libreofficom bude v subore `chcemvediet/apps/anonymization/content_types.py` v poli `LIBREOFFICE_CONTENT_TYPES`. Zatial tam daj nejake podporovane content types, nech mame konverziu ako testovat. Cely zoznam skompletizujeme v #178.

Samotnu konverziu vykoname commandline prikazom:
```
libreoffice --headless --convert-to pdf --outdir /{path} {input}
```
Libreoffice skonvertovany subor sa ulozi do `/{path}/{input}.pdf`. Vstupny subor pred konverziou pre istotu skopiruj do tempu, nech nahodou libreoffice vo vstupnom subore nieco neposaha. Skopirovany subor premenuj na nejaky rozumny nazov aj s priponou zistenou na zaklade `Attachment.content_type` pomocou `guess_extension`. V ziadnom pripade nepouzivaj nazov `Attachment.name`, ten pochadza z nedoverihodneho zdroja a boze byt v nom akykolvek bordel. Vysledny subor si tiez nechaj ulozit do tempu a potom ho odtial precitaj.

Co som testoval libreoffice, tak vyzera, ze ziadne rozumne navratove hodnoty nevraca. Ci konverzia prebehla uspesne alebo nie zistis iba podla toho, ci vysledny subor sa objavil alebo nie. Poriadne sa teda uisti, ze adresar kam ides ukladat vysledny subor je pred konverziou prazdny. Pri praci s temp adresarom davaj pozor aby nenastali race conditions a nepoprepisoval si si nejake subory a nenechal na konci bordel.

Po uspesnej konverzii vysledny subor precitaj a uloz ho do `AttachmentNormalization.file`. Pocas konverzie zaznamenavaj aj stdout a stderr a vsetko, co sa tam zapise uloz do `AttachmentNormalization.debug`, nech si to vieme v pripade potreby pozriet.

Na koverziu treba spravit casovy limit, napriklad 5 minut, pre pripad, ze sa libreoffice zacykli, alebo by mu konverzia trvala prilis dlho. Ak konverzia v casovom limite neskoci, command treba zabit a do `debug` napisat ze konverzia timeoutla.

Ak sa Ti podari najst nejaky elegantnejsi sposob, ako spravit konverziu cez libreoffice, pouzi ho. Idealne keby sa dalo temp suborom uplne vyhnut a s libreoffice komunikovat iba cez stdin/stdout alebo ine pipy. Ale co som pozeral dokumentacie, tak to asi nevie.

Ak sa konverzia podari, vyvor `AttachmentNormalization`:
- `attachment`: FK na `attachment`
- `successful`: true
- `file`: data z PDF ziskaneho konverziou
- `content_type`: PDF
- `debug`: vystup na stdout/stderr z konverzie
- Ostatne fieldy sa doplnia automaticky v `AttachmentNormalization.save`.

Ak sa konverzia nepodari, vyvor `AttachmentNormalization`:
- `attachment`: FK na `attachment`
- `successful`: false
- `content_type`: PDF
- `debug`: vystup na stdout/stderr z konverzie
- Ostatne filedy ostanu NULL okrem `created`, ktory sa automaticky doplni v `save`

**Comment by viliambalaz** [comment]
Mozem teraz pouzit pre nazov suboru `Attachment.name`, kedze uz je bezpecne ?

**Comment by martinmacko47** [comment]
> Mozem teraz pouzit pre nazov suboru `Attachment.name`, kedze uz je bezpecne ?

Nazov akeho suboru? Ak myslis nazov suboru na disku, tak nie, tie budeme mat nadalej generovane.
