### ISSUE TITLE
OCR znormalizovaneho attachmentu

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#184]
**Depends on: #173, #181, #180, #183**

### Model pre OCR verziu attachmentu

Analogicky ako v #173 spravit model `AttachmentRecognition` s rovnakymi fieldami ako ma `AttachmentNormalization`. Field `file` sa bude ukladat do adresara `attachment_recognitions`.

Analogicky sprav aj metody/properties a komentare k modelu, query set, migraciu, datachecks, admin obrazovku a dopln dokumentaciu.

### Devel (trial) verzia ABBY

V produkcii mame kupenu produkcnu verziu ABBY. Ale aby si to mohol pocas developovania testovat lokalne u seba, potrebujes devel (trial) verziu ABBY. Instalacku aj trial seriove cislo Ti dam. Nainstaluj a vyskusaj si ju lokalne. Silne odporucam instalovat si ju do virtualky, pretoze vyzaduje roota. Aby si si nezaprasil system. Navod na instalaciu ti dam spolu s instalackou.

Pozor trial verzia ma limit 100 stran. Takze pri skusani setri a pouzivat len jedno-dvoj stranove dokumenty. A netestuj prilis vela. 

### Cron job na OCR priloh

Rozsirit cron job vytvoreny v #181 aby na konci po znormalizovani nekej prilohy, nejaku prilohu OCRkol.

Cize po skonceni normalizacie, bez ohladu na to, ci bola uspesna alebo neuspesne, cron job selectne nejaky `AttachmentNormalization` so `successful` true a `content_type` PDF, pre ktory este neexistuje ziadny `AttachmentRecognition` pre rovnaky `Attachment`, a pokusi sa ho OCRknut. Pozor v buducnosti mozu mat normalizovane subory aj ine typy nez PDF, preto pri selectovani treba zobrat iba PDF. Priloha, ktoru selectneme na OCRkovanie nemusi byt ta ista, ktoru sme prave znormalizovali. Obe ulohy mame v spolocnom cron jobe iba koli tomu, aby nenastavali race conditions ak by sa dva nezavisle cron joby spustili paralelne.

Samotnu konverziu spravime analogicky ako konverziu na pdf v #180 akurat s ABBY OCR CLI toolom cez commandline prikaz:
```
abbyyocr11 --recognitionLanguage Slovak --splitDualPages -if {input}.pdf -f ODT --rtfKeepLines --rtfRemoveSoftHyphens --rtfPageSynthesisMode ExactCopy -of {output}.odt
```

Vsetky veci okolo prace s temp subormi, stdout/stderr vystupom a podobne treba spravit analogicky ako v #180. Konverziu povazujeme za failnutu, ked vrati chybovy exit status, alebo nevytovri vysledny subor. Nezabudni na koverziu aplikovat nejaky casovy limit. Povedzme 5 minut.

Po uspesnem aj neuspecnom OCR vytvorit instanciu `AttachmentRecognition` s vysledkom OCR a `content_type` ODT analogicky ako v #182 vytvarame instancie `AttachmentNormalization`.

### Mock OCR

Na konci analogicky ako v #183 treba pridat moznost OCR iba mockovat.

**Comment by martinmacko47** [comment]
@viliambalaz Task zatial nezatvaram, kym ho neotestujes so skutocnym `abbyyocr11`, nie len s mockom. Pristup k produkcnemu `abbyyocr11` sa riesi. 

Vid: https://github.com/martinmacko47/chcemvediet/pull/201#discussion_r312125405

**Comment by martinmacko47** [comment]
@viliambalaz Teraz, ked mas uz pristup k OCR, pls vyskusaj, ci implementovana feature funguje. A napis zaver sem do komentara.

**Comment by viliambalaz** [comment]
@martinmacko47 , OCR recognition prebehla uspense :), vyskusal som jednu prilohu OCR-kovat aj priamo cez terminal s exit status 0

**Comment by martinmacko47** [comment]
Super
