### ISSUE TITLE
Anonymizacia OCR attachmentu 

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#185]
**Depends on: #184**

### Model pre anonymizovanu verziu attachmentu

Analogicky ako v #184 spravit model `AttachmentAnonymization` s rovnakymi fieldami ako ma `AttachmentRecognition`. Field `file` sa bude ukladat do adresara `attachment_anonymizations`.

Analogicky sprav aj metody/properties a komentare k modelu, query set, migraciu, datachecks, admin obrazovku a dopln dokumentaciu.

### Cron job na anonymizaciu priloh

Cron job na OCR z #184 treba rozsirit o anonymizaciu. Po skonceni OCR (ci uz uspesnom alebo neuspesnom) cron job selectne nejaky `AttachmentRecognition` so `successful` true a `content_type` ODT, pre ktory este neexistuje ziadny `AttachmentAnonymization`, a pokusi sa ho anonymizovat. Pre istotu pri selectovani treba brat do uvahy iba `AttachmentRecognition`, ktore su OCRknute do ODT, ak by v buducnosti boli aj ine content type OCR suborov, ktore treba anonymizovat inac. Priloha, ktoru selectneme na anonymizovanie nemusi byt ta ista, ktoru sme prave OCRkovali. Obe ulohy mame v spolocnom cron jobe iba koli tomu, aby nenastavali race conditions ak by sa dva nezavisle cron joby spustili paralelne.

Samotnu anonymizaciu spravime tak, ze ODT subor rozzipujeme pomocou kniznice [`zipfile`] a upravime. Pri rozzipovavani pouzi [`stringio`], aby si nemusel pracovat s temp subormi. Pomocou `stringio` vyrobis file-like objekt, ktory dat ako vstup pre `zipfile`, a z ktoreho nakoniec precitas upraveny zip subor, ktory ulozis do DB.

V rozpakovanom ODT prejdi vsetky subory s pripomou `.xml` a rozparsuj ich pomocou [`xml.etree.elementtree`]. Nevytvaraj ziadne pomocne subory, vsetko by malo ist cez file-like objekty alebo stringy. V jednotlivych XML najdi `text:span` elementy a zanonymizuj ich textovy obsah. Pozor `text:span` elementy mozu obsahovat dalsie podelemety. Tie chces zachovat a zcenzurovat iba text medzi child elementami.

[`zipfile`]: https://docs.python.org/2.7/library/zipfile.html
[`stringio`]: https://docs.python.org/2/library/stringio.html
[`xml.etree.elementtree`]: https://docs.python.org/2/library/xml.etree.elementtree.html

Zatial budeme anonymizovat iba meno, priezvisko a adresu ziadatela. Najdes ich tak, ze k prilohe selectnes `Action`, ku ktorej patri, k `Action` selectnes prislusny `Inforequest`, a cez `Inforequest.applicant` instanciu `User` z ktorej zistis udaje ziadatela. Konkretne budeme anonymizovat tieto stringy:
- `User.first_name`
- `User.last_name`
- `User.profile.street`
- `User.profile.city`
- `User.profile.zip`
- `Inforequest.applicant_name` (tieto su frozen udaje ziadatela v case podania ziadosti)
- `Inforequest.applicant_street`
- `Inforequest.applicant_city`
- `Inforequest.applicant_zip`

Anonymizaciu v samotnom texte spravis tak, ze v texte najdes anonymizovane stringy a nahradis ich stringom `"xxxxx"`. Pocet znakov `x` je fixny bez ohladu na dlzku anonymizovaneho stringu. Pri anonymizovani neber ohlad na velke a male pismena. Takisto neber ohlad na nealfanumericke znaky.

Ak meno ziadatela obsahuje viac slov, rozdel ich a jednotlive slova anonymizuj samostatne. Ak ulica alebo mesto obsahuju viac slov, anonymizuj ich ako cele slovne spojenia. Ak ZIP obsahuje medzeru, medzeru ignoruj. Pri hladani ZIPu v texte tiez ignoruj medzeru v texte. 

Po uspesnej aj neuspecnej anonymizacii vytvorit instanciu `AttachmentAnonymization` s vysledkom anonymizacie a `content_type` ODT analogicky ako v #184 vytvarame instancie `AttachmentRecognition`.

**Comment by viliambalaz** [comment]
@martin Moze nastat pripad ked anonymizacia bude neuspesna? V podstate tu len nahradzame stringy inymi. Pracujeme len s takymi `AttachmentRecognition`,  ktore su uspesne, cize maju svoj existujuci `.odt' subor.

**Comment by martinmacko47** [comment]
> @martin Moze nastat pripad ked anonymizacia bude neuspesna? V podstate tu len nahradzame stringy inymi. Pracujeme len s takymi `AttachmentRecognition`, ktore su uspesne, cize maju svoj existujuci `.odt' subor.

Ano. Kod, ktory riesi samotnu anonymizaciu (rozzipovanie, search, zazipovanie) moze raisnut exception (napriklad nevalidny zip). Preto ho treba obalit do `try`/`except` a pripadnu chybu zalogovat.

**Comment by viliambalaz** [comment]
@martin ma zmysel uvazovat o situacii, ked ZIP `User.profile.zip` resp. `Inforequest.applicant_zip` bude obsahovat medzeru?  Formular pri vytvarani noveho uzivatela akceptuje format `r'\d{5}'`, teda 5 cifier za sebou bez medzery.

**Comment by martinmacko47** [comment]
@viliambalaz Sice ak to formular nedovoli, tak mozeme predpokladat, ze tam medzera nie je. Ale pre istotu by som ZIP hodnoty aj tak radsej explicitne prefiltroval s [`translate`] alebo tak nejak.

[`translate`]: https://docs.python.org/2/library/string.html#string.translate
