### ISSUE TITLE
Docx savnuty v libreoffice je identifikovany ako ZIP

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#195]
Ked priloha bola savnuta v libreoffice ako docx, tak ho identifikujeme ako `application/zip`. Treba vymysliet/vygooglit ako take subory identifikovat spravne.

Priklad takeho suboru: [aaa.docx](https://github.com/martinmacko47/chcemvediet/files/3435533/aaa.docx)

Savnuty bol ako:
![docx](https://user-images.githubusercontent.com/5547275/61948880-59a79700-afa9-11e9-8fc6-cda2b7f5e8f6.png)

Verzia pouziteho libreoffice: 4.2.8.2

**Comment by viliambalaz** [comment]
Ja som s tymto nemal problem. Mam nainstalovany `LibreOffice 5.1.6.2 10m0(Build:2).`
[report.pdf](https://github.com/martinmacko47/chcemvediet/files/3461089/report.pdf)

**Comment by martinmacko47** [comment]
Vyzera, ze problem je vo verzii `libmagic` v systeme. Ja mam 5.14 a na nej subor identifikuje zle. Ked som to skusil na virtualke s verziou `libmagic` 5.25, tak to subor identifikovalo spravne.

Pls pozri aku mas Ty: `$ file --version`.

Fixneme to teda tak, ze do README doplnime, ze treba verziu `libmagic` aspon 5.25

**Comment by viliambalaz** [comment]
ano moja verzia je 5.25
```
$ file --version
file-5.25
magic file from /etc/magic:/usr/share/misc/magic
```
Pri dalsom testovani som vsak narazil na podobne chyby ked som si v libreoffice skusal vsetky mozne prilohy, ktore mi libreoffice umoznil ulozit z writer, excel, presentation, draw, math a database, konkretne sa jedna o: 
```
ext:.xlsx mime: application/octet-stream
ext:.odb mime: application/octet-stream
ext:.xlsm mime: application/octet-stream
```

**Comment by martinmacko47** [comment]
`.odb` a `.xlsm` asi netreba. Ale `.xlsx` by sa zislo. Je to asi chyba v `libmagic` ze ich nepozna. Zatial teda na to kaslime, len doplnme info do readme. S vysvetlenim, ze starsie verzie mozu sposobit, ze niektore typy suborov nebudu spravne identifikovane.

Ak sa ti chce, mozes to reportnut ako bug do `libmagic`, nech to fixnu. Predtym si pre istotu over, ze to stale nefunguje ani v najnovsej verzii.

**Comment by viliambalaz** [comment]
K comu som sa dopatral :
[link 1](https://stackoverflow.com/questions/17779560/django-python-magic-identify-ppt-docx-word-uploaded-file-as-application-zip)
[link 2](https://serverfault.com/questions/338087/making-libmagic-file-detect-docx-files/377792#377792)
V skratke:
novsie verzie linuxu by nemali mat problem rozpoznavat wordovske subory .docx, .xlsx, ...
mozeme pridat dodatocne informacie `file` prikazu na identifikovanie tychto suborov pridanim instrukcii do `/etc/magic`

V mojom pripade sa mi teraz subor .xlsx podarilo ulozit spravne a aj som ho dokazal znormalizovat. Avsak po uprave etc/magic sa subory .otg, .odg subory vyhodnotia ako `application/octet-stream`, pricom pred upravou `etc/magic` sa tieto typy suborov vyhodnotili spravne

**Comment by martinmacko47** [comment]
Ok. Doriesime to neskor. Zatial len do README napis, ze potrebujeme dostatocne novu verziu `libmagic`. A potom uvidime v produkcii, ako to pojde. Ak bude vela suborov, ktore budu robit problemy, rucne doplnime pravidla do `/etc/magic`
