### ISSUE TITLE
Prepisanie dokumentacie do markdown

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#203]
Prepis vsetky `misc/*.odt` do markdown + SVG podobne ako sme prepisali `misc/attachments.md`. A stare ODT subory zmaz. 

Casti textu oznacene "To Do" oznac ako preciarknute `~~foo~~`. A na konci dokumentu, v ktorom su nejake To Do veci, daj poznamku, ze takto oznacene veci este nie su implementovane. Ak ti napadne lepsi sposob ako oznacit To Do veci, pouzi ho. (pociaknutie nefunguje, bold pouzivame na ine ucely a italics je nevyrazne).

Kazdy subor rob radsej v samostatnom PR. Zacni mensimi subormi. 

V `inforequests.odt` su dva obrazky. Na prvom je DB model a na druhom Inforequest Flow. Ten druhy diagram s Inforequest Flow neprekresluj, kedze je neaktualny. Novsiu verziu mame v `inforequest-flow.odg` a prekreslime ju do SVG neskor.

**Comment by viliambalaz** [comment]
@martinmacko47 Co treba robit so subormi `obligee-action-wizard.odg`, `appeal-wizard.odg`? Kedze chceme opakovat akcie institucie, tieto wizard diagrami sa este budu menit vsak?

**Comment by martinmacko47** [comment]
> @martinmacko47 Co treba robit so subormi `obligee-action-wizard.odg`, `appeal-wizard.odg`? Kedze chceme opakovat akcie institucie, tieto wizard diagrami sa este budu menit vsak?

`obligee-action-wizard.odg` a `appeal-wizard.odg` zatial nechajme tak ako su, kedze sa budu asi menit. Zbytocne ich teraz prekreslovat.

**Comment by viliambalaz** [comment]
@martinmacko47 
V dokumentacii `inforequests.odt` je opisany model `ActionDraft`. Ten sa vsak vobec nepouziva a v [migracii 0008](https://github.com/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/migrations/0008_auto_20150819_1949.py#L26) sa vymaze. Co teraz(do buducna) s tym? Zatial to chcem nechat lebo v tomto issue len prepisujeme dokumentaciu.

**Comment by martinmacko47** [comment]
> V dokumentacii `inforequests.odt` je opisany model `ActionDraft`. Ten sa vsak vobec nepouziva a v [migracii 0008](https://github.com/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/migrations/0008_auto_20150819_1949.py#L26) sa vymaze. Co teraz(do buducna) s tym? Zatial to chcem nechat lebo v tomto issue len prepisujeme dokumentaciu.

Dobry postreh. Na tom som uz aj zabudol. Ano bol nahradeny modelom [`WizardDraft`] v samostatnej app `wizards`, kedze tie drafty su vyrazne vseobecnejsie, nez predpokladal model `ActionDraft`. Zatial to v dokumentacii pls nechaj, len daj k tomu nejaku znacku a na konci dokumentu daj footnote s tou znackou, ze `ActionDraft` bol nahradeny `WizardDraft`.

Ked budeme mat niekedy cas, tak dokumentaciu aktualizujeme, doplnime `WizardDraft` (do samostatneho suboru, kedze je to samostatna app) a vyhodime `ActionDraft`. Ale zatial to neriesme.

**Comment by martinmacko47** [comment]
@viliambalaz Cize vsetky dokumentacie mame prepisane? Okrem teda flow chartov, ktore zatial neprekreslujeme.

**Comment by viliambalaz** [comment]
> @viliambalaz Cize vsetky dokumentacie mame prepisane? Okrem teda flow chartov, ktore zatial neprekreslujeme.
@martinmacko47 Ano, vsetky dokumentacie uz mame prepisane, okrem flow chartov.
