### ISSUE TITLE
subprocess32.run by malo kontrolovat ci tool nefailol

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#206]
Aktualne `subprocess32.run` povoli aby commandline tool skoncil s non-zero result kodom. Staci, ze tool vytvoril pozadovany subor. Imho mali by sme aj kontrolovat, ci tool nevratil nejaky chybovy stav. Lebo kludne sa moze stat, ze tool zacne do suboru nieco zapisovat a podom padne.

Ak spravne chapem, do `subprocess32.run` by malo stacit vsade pridat `check=True`. Python potom raisne exception ak tool vrati non-0 status code. Exception potom standardne odchytime a zalogujeme ako akukolvek inu exception.

Pls pretestuj, ci vsetky pouzivane commandline tooly vracaju vzdy pri uspechu status code 0.

**Comment by viliambalaz** [comment]
Skontrolovane, status code je pri uspechu 0.
