### ISSUE TITLE
Vyhladavanie cez google custom search

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#209]
Implementovat vyhladavanie na webe cez [google custom search]. Pouzit vytvoreny custom search: https://cse.google.com/cse/setup/basic?cx=010601888809869439804%3Ark-fpmmkuio  Ked s tym zacnes robit, napis, ze ti nastavim prava na pristup ku fonfiguracii custom searchu.

[google custom search]: https://developers.google.com/custom-search/docs/tutorial/introduction

Ako searchbox pouzi zatial nefunkcny searchbox co je v pravom hornom rohu webu:

![searchbox](https://user-images.githubusercontent.com/5547275/63347829-45f91180-c358-11e9-918b-66bd3bf38ec0.png)

Pre zobrazenie vysledkov sprav novy view, na ktorom zobrazis google widget s vysledkami. View bude mat rovnaky header a footer ako ostatne obrazovky.

**Comment by viliambalaz** [comment]
Pre custom search engine som zmenil layout z `Overlay` na `Results only`.
