### ISSUE TITLE
text of appeal should be generated

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#21]
* include user details
* what happened (history of the case) - "User has reqested, X has refused, User appealed, etc."
* what institution stated as a reason for refusal: Include pre-generated text according to law for the selected reasons.

The user obtains the generated document, edits it to match his/her needs, prints, sends.

**Comment by martinmacko47** [comment]
We should meet and prepare decision tree.

**Comment by mmmaly** [comment]
the same for clarification response.

**Comment by martinmacko47** [comment]
@mmmaly pls provide examples of appeal texts as I asked at the meeting. For clarification response make a separate issue pls.

**Comment by martinmacko47** [comment]
@mmmaly wll you manage to have it prepared at friday?

**Comment by mmmaly** [comment]
yes

**Comment by mmmaly** [comment]
template of appeal attached here: https://dl.dropboxusercontent.com/u/39647189/appeal_template.docx
Yellow text is notification for the user to modify. Text in [square brackets] refers to values. Text in {curly brackets} refers to conditions.

I will also add explanatory message for the user along the lines: "Please review yellow marked text, edit it or remove as instructed. The text instructs you as best as it could be automatized; please follow the instructions. Do not use those formulations which are not relevant to your case. If you find that the text provided does not support your argument, remove it. You are invited to more arguments. Also please consider the possibility that the resolution provided was lawful, do not unnecessarily argue against common sense. "

**Comment by martinmacko47** [comment]
Seems done. Please checks everything is done as expected.

**Comment by mmmaly** [comment]
wizard works.
