### ISSUE TITLE
Automaticke zverejnovanie ziadosti

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#212]
**Depends on: #207**

Spravit cron job, ktory 2 mesiace po uzatvoreni ziadosti ju automaticky oznaci ako zverejnenu. Ziadost je uzatvorena, ked je `Inforequest.closed` true. Ziadost sa uzatvara automaticky v cron jobe [`close_inforequests`], ked sa splnia podmienky na jej uzatvorenie.

[`close_inforequests`]: https://github.com/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/cron.py#L167

Novy cron job spravit do toho isteho suboru ako je `close_inforequests` a nazvat ho napriklad `publish_inforequests`. Cron job sa bude kazdy den v `CRON_IMPORTANT_MAINTENANCE_TIMES`.

Nakoniec pridaj boolean setting `AUTOPUBLISH_INFOREQUESTS`, ktory v `settings/common.py` bude `True` ale v `settings/server_prod.py` bude overridnuty na `False`. Cronjob bude automaticky zverejnovat ziadosti iba ak `AUTOPUBLISH_INFOREQUESTS` je `True`. Setting fo `settings/common.py` pridaj niekde na koniec. V `settings/server_prod.py` niekam za setting `INVITATIONS_INVITATION_ONLY`.

**Comment by martinmacko47** [comment]
Este mi napadlo, ze bude treba este implementovat sposob, ako zabranit cronu publikovat niektore konkretne infoziadosti. Aby admin mal moznost v DB nastavit, ze niektore infoziadosti sa nikdy zverejnovat nebudu.

Navrhujem v upravit nasledovne:

Upravit field `Inforequest.published` aby bol NULL-able, pricom:
   - `NULL` znamena, ze inforequest nie je zverejneny, ale casom sa automaticky zverejni
   - `False` znamena, ze inforequest nie je zverejneny, ani sa **nikdy automaticky nezverejni**
   - `True` znamena, ze inforequest je zverejneny

Pricom defaultna hodnota `Inforequest.published` by bola `NULL`. A hodnotu `False` by mohol nastavit iba rucne admin v admin rozhrani.

Treba upravit model, migraciu, cron job a mozno aj admin rozhranie. Pri uprave migracie by bolo asi vhodne prepisat povodnu migraciu `0022_inforequest_published`, aby nedavala existujucim infoziadostiam automaticky hodnotu published `False`, ale `NULL`. Mozeme si to dovolit, kedze migracia `0022_inforequest_published` este nie je v produkcii.

Toto pls rob s samostatnom PR po mergnuti #229.

**Comment by viliambalaz** [comment]
@martinmacko47 Navrhoval by som len prehodit vyznam `NULL` a `False`. Tym padom bude treba spravit menej uprav v kode.
