### ISSUE TITLE
Text k zoznamu zverejnenych ziadosti

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#225]
Pls napis nam aky sprievodny text dat medzi nadpis a samotny zoznam zverejnenych infoziadosti. Asi by sa hodilo sem napisat, kedy a ako sa ziadosti zverejnuju, ze su anonymizovane a podobne. Zisiel by sa tak jeden az dva odstavce textu. Aspon teda nejaky text nateraz. Neskor ho mozeme upravit. Konkretne ide o text, ktory bude tu:

![zverejnene](https://user-images.githubusercontent.com/5547275/66923946-07b36200-f02a-11e9-985c-c48423aa6b5f.png)

V kode je ten text v templatoch `chcemvediet/apps/inforequests/templates/inforequests/index/texts/index.{sk,en}.html`. Mozes napisat obe jazykove verzie, alebo len slovensku. Ak napises len slovensky text, tak lokalizovane templaty `index.{sk,en}.html` nahrad jednym `index.html`

**Comment by mmmaly** [comment]
jasne, nieco napisem a commitnem. Zatial draft na https://docs.google.com/document/d/1dO5XyPrF3dJx656A6ywXSk5LFjylkMgcPhzOcDgo3-I/edit

**Comment by martinmacko47** [comment]
@mmmaly Len taka drobnost. Nezacitaj vetu zacinat "tu sa nachadza", ved je jasne, ze "tu". Zacni ju priamo podmetom. Vid ako je to v zozname institucii. 

Tiez je dobre sa vyvarovat zatvorkam a potobnym barlickam. Radsej to co je v zatvorke napisat v dalsej samostatnej vete. Tazko sa citaju take komplikovane vety.

**Comment by martinmacko47** [comment]
@viliambalaz V google docs na linke spomenutej vyssie v komentari od @mmmaly je uz hotovy text. Pls sprav PR, co ho tam zobrazi. Issue teda priradzujem dalej Tebe.
