### ISSUE TITLE
Nastavenie: Vypnutie anonymizovania

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#231]
Rozsirit model `Profile` (definovany v `chcemvediet/apps/accounts/models.py`) o boolean field `anonymise_inforequests`. Defaultne a aj pre uz existujucich userov bude mat field hodnotu true.

Do menu pridat polozku "Nastavenia", ktora bude smerovat na novu obrazovku `/sk/accounts/nastavenia`:

![menu](https://user-images.githubusercontent.com/5547275/71547465-8caee600-29a0-11ea-9790-bbb8e26506ef.png)

Obrazovka nastavenia by mala byt formatovana analogicky ako napriklad obrazovka na zmenu hesla alebo obrazvoka na spravovanie emailov.

Obrazvoka by mala mat zatial iba jedno nastavenie: checkbox, ci anonymizovat ziadosti. A button na ulozenie nastaveni. Text settingu zatial daj nejaky, doladime ho neskor.

Nakoniec treba upravit zobrazovanie zverejnenych ziadosti, aby ziadosti uzivatelov s vypnutou anonymizaciou sa zobrazovali neanonymizovane. Ziadosti uzivatelov so zapnutou anonymizaciou sa budu zobrazovat anonymizovane ako doteraz.

**Comment by viliambalaz** [comment]
@martinmacko47 Ak uzivatel chce aby niektore zjadosti boli anonymizovane a niektore nie? Pridame tam takuto moznost?

**Comment by mmmaly** [comment]
@viliambalaz: myslim, ze zatial sme sa s Matom dohodli, ze netreba -- ak niekto pocituje potrebu, moze urobit workaround, ze si spravi dve konta, kde jedno sa nebude a jedno bude anonymizovat.

**Comment by martinmacko47** [comment]
> @martinmacko47 Ak uzivatel chce aby niektore zjadosti boli anonymizovane a niektore nie? Pridame tam takuto moznost?

Ako pise @mmmaly nateraz nie. Bud user bude mat vsetky ziadosti anonymizovane, alebo vsetky neanonymizovane. V buducnosti mozno pridame moznost (ne)anonymizovat aj per ziadost, ale zatial nie.
