### ISSUE TITLE
Nastavenie: Custom anonymizovane stringy

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#232]
V #231 sme spravili obrazovku nastavenia. Na obrazovku doplnit nove nastavenie, zoznam stringov, ktore sa budu anonymizovat.

Nastavenie zobraz ako dvojicu fieldov:
- Checkbox, ci pouzivat defaultne stringy z `generate_user_pattern`. V popise pri checkboxe napis ze defaultne sa bude anonymizovat meno, priezvisko a adresa uzivatela.
- Textarea, ktora sa zobrazi iba ked user zaklikne za nechce pouzivat defaultne stringy. V textarei bude kazdy riadok samostany pattern na anonymizovanie. Skryvanie textarei sprav analogicky ako mame spravene skryvanie fieldov vo wizarde. Ku textarei by sa zislo napisat odstavec textu, ako budu zadane slova anonymizovane (napr. ze velkost pismen a diakritika sa ignoruju, slova zadane v jednom riadku musia ist za sebou a interpunkcia medzi nimi sa neignoruje, slova zadane v samostatnych riadkoch sa anonymizuju samostatne. A podobne. Zatial napis ako zvladnes, potom to doladime).

Sprav zakladnu normalizaciu a validaciu zadanych stringov: 
- orez medzery na zaciatkoch a koncoch riadkov
- vynechaj prazdne riadky
- zakaz riadky kratsie ako `WORD_SIZE_MIN` resp. `NUMBER_SIZE_MIN`
- zamysli sa, aku dalsiu validaciu by sa zislo

Nastavenie sa v DB ulozi do modelu `Profile` rovnako ako ostatne nastavenia. Pouzi postgres typ [array of strings](https://www.postgresql.org/docs/9.1/arrays.html). Takze v jednej DB bunke budu vsetky stringy. Stlpec bude nullable a hodnota NULL bude znamenat, ze user pouziva na anonymizovanie defaultne stringy. Defaultne (a pre uz existujucich userov) bude nastavenie mat hodnotu NULL.

Uprav logiku v `generate_user_pattern` aby sa pouzili nastavene stringy a defaultne iba ak nastavene stringy su NULL. Ak niektory string obsahuje iba cisla a pripadne medzery a ine nealfanumericke znaky, tak ho aplikuj cez `generate_numeric_pattern` inac cez `generate_word_pattern`. Zadane slova vsak nijak nesplituj, ak user chce, splitne si ich sam do samostatnych riadkov.

Nakoniec, ak user zmeni anonymizovane stringy, tak z DB zmaz anonymizacie a finalizacie priloh zo vsetkych userovych ziadosti. Aby cron ich preanonymizoval znovu. Zmaz ich vsak iba ked user naozaj stringy zmeni. Ak ich savne nezmenene, tak nemaz nic.

**Comment by viliambalaz** [comment]
@martinmacko47 `django.contrib.postgres` je az od verzie django **1.8**. Nasa verzia je **1.7.4**. Ako to vyriesime? Pouzijeme obycajny `CharField` + pridame `@cached_property`, ktora vrati list so stringami?

**Comment by martinmacko47** [comment]
@viliambalaz Namiesto toho mozeme pouzit `JSONField` s polom stringov. Vid napriklad `InforequestDraft.subject`.
