### ISSUE TITLE
Zrusit limit na odpoved od institucie

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#234]
**Depends on  #275 and #279**

**Comment by mmmaly** [comment]
lahke rozhranie pre admina zmazat Expiration.

**Comment by martinmacko47** [comment]
Po implementacii #275 a #279 bude rusenie limitu na odpoved od institucie fungovat nasledovne:

1. Najprv predlzi snooze na akcii s expirovanym deadlinom tak, aby snooze date nebol v minulosti.
2. Potom zmaze prislusnu `EXPIRATION` resp. `APPEAL_EXPIRATION` akciu. Zmazana akcia sa nevytvori nanovo, kym opat nevyprsi predlzeny snooze.

Takze extra tool na to netreba. Admin to vyklika v dvoch krokoch.

**Comment by martinmacko47** [comment]
@mmmaly Tasky #275 a #279 su hotove a mergnute do mastra. Pls pretestuj, ci vyssie popisany postup funguje a postacuje.

**Comment by mmmaly** [comment]
No, asi to funguje... Ale neviem, ci je to "lahke", aby som to vedel niekomu rychlo vysvetlit. Teda urcite je to lepsie nez predtym, a ked clovek vie, co robi, tak ok -- neviem vsak, ci pre zaciatocnika "lahke": Stale to vyzaduje asi 14 kliknuti.

0 (neratam): Otvorit branchu.
kliknut action (1), zaskrolovat dole, lebo je to vacsinou dlhe alebo kliknut na scrollbar (2), kliknut zmazat (3), potvrdit (4). Kedze sme zmazali, tak sa ukaze dlhy zoznam vsetkych branchi, takze najlahsie je kliknut 2x v browseri naspat (5,6) aby som sa dostal zase na branchu. Teraz sa cloveku ziada refresh, lebo browser si pamata, takze stale vidim zmazanu akciu, po refreshi (7) samozrejme zmizne. Potom kliknut (8) tu poslenu akciu pred tym, zaskrolovat na snooze, kliknut napriklad Dnes (9), potom kalendar (10), potom mesiac vpred povedzme dvakrat (11,12) a potom kdesi do kalendara na potvrdenie (13) a ulozit (14).

Takto to bolo myslene, ci je nejaky lahsi sposob?

**Comment by martinmacko47** [comment]
Ano, akurat len v opacnom poradi: najprv predlzit snooze a potom zmazat expiration. Aby sa nehodou expiration medzicasom znovu nevytvorilo, ak nahodou klikas v noci prave pocas behu cron jobu, co ich pridava. Niektore kliky vies usetrit otvorenim niektorych liniek cestou v novom tabe. Ale nie zasadne vela.

Bohuzial (alebo bohuvdaka?) taky je Django admin. Da sa v nom spravit skoro vsetko, ale nie jednoducho. Musis vediet presne, co chces spravit a musis davat pozor, aby si nespravil nieco nespravne. Je to iba logicka abstrakcia nad DB pre power userov, nie easy-to-use fail-safe rozhranie pre bezny customer support.

V principe mozeme v detaile expiration akcie spravit novy button "zmazat expiration a predlzit sznooze predoslej akcie". Akurat s pribudajucim mnozstvom roznych ukonov, bude takych buttonov pribudat a zacne to byt neprehladne. Plus zivy clovek lahsie postrehne rozne okrajove pripady, ze nieco tam nesedi, nez automat. 

Co som videl komercne pouzivany Django admin, tak zvycajne tie firmy mali interne how-to dokumentacie, ako krok po kroku spravit pravidelne sa opakujuce ukony v admine. Aby customer support to vedel podla navodu spravne vyklikat. Dovod bol vraj taky, ze how-to dokumentacie su pruznejsie, nez automaticke akcie. A mozes tam napisat kroky typu "zamysli sa ci" a podobne.

Spravit teda taky button? Ci zacneme spisovat how-to postupy pre adminov?

**Comment by mmmaly** [comment]
Mne by sedelo urobit taky button. Resp. par buttonov na povedzme 90% najcastejsich akcii. Lebo potom napr. lahko niekomu vysvetlim par buttonov, a oni budu vediet robit 90% veci a ten zvysok 10% komplexnych prestudujem a spravim sam.

**Comment by martinmacko47** [comment]
@mmmaly Skusime nieco spravit. Vid #310. O kolko sa ma predlzit snooze predoslej akcie po zmazani expiration? Staci na aktualny datum plus 7 dni? Alebo treba viac/menej?

**Comment by martinmacko47** [comment]
@mmmaly Hotovo. Po mergnuti PR #327 bude na confirm obrazovke pri deletovani expiration nasledujuci checbox:

![delete-expiration](https://user-images.githubusercontent.com/5547275/99443828-a12f0080-291b-11eb-8b6f-e53a3a84f526.png)

Po jeho zaskrtnuti sa zvysi snooze predoslej akcie, pred danym expiration tak, aby akcia expirovala o 10 kalendarnych dni od datumu zmazania expiration. Ten pocet 10 dni mozeme zmenit ak chces.

Pls po mergnuti PR #327 to pretestuj.

**Comment by martinmacko47** [comment]
*label `testing` rusim, stav issue nahradza [stlpec v boarde](https://github.com/martinmacko47/chcemvediet/projects/2#column-12139874)

**Comment by mmmaly** [comment]
Otestovane, funguje.
