### ISSUE TITLE
Admin: preklasifikovat odpoved ako nieco ine

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#235]

**Comment by martinmacko47** [comment]
@mmmaly Preklasifikovanie typu odpovede by malo fungovat uz teraz. Staci v detailne akcie `/admin/inforequests/action/{ID}/` zmenit "Type" akcie na iny a savnut:

![preklasifikovanie](https://user-images.githubusercontent.com/5547275/81397545-da461700-9127-11ea-9d60-6e8ed7dc3bcf.png)

Akurat pozor, ze ak odpoved preklasifikujes silno. Napriklad postupenie na zamietnutie, tak vsetky ostatne fieldy ostanu nezmenene. Napriklad sa ti moze podarit vyrobit zamiestnutie s postupeniami dalsim instituciam. Cize pri zmene typu akcie si treba davat pozor aj na ostatne fieldy, ci maju rozumne hodnoty.

Pls pretestuj, ci to funguje.

**Comment by martinmacko47** [comment]
@mmmaly Pls pretestuj to, nech to mozeme uzavriet

**Comment by mmmaly** [comment]
Funguje
