### ISSUE TITLE
Formular na navrh pridania/opravy institucie

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#236]

**Comment by mmmaly** [comment]
mm: google form, cize staci obrazovka, kde dame odkaz.

**Comment by martinmacko47** [comment]
@mmmaly Pls priprav ten google form. Nech si ho vieme vyskusat ako funguje a potom zakomponovat niekam do webu.

**Comment by mmmaly** [comment]
https://forms.gle/pQKEHgAqvNZfF5ue9
ad account: Chceme specialneho uzivatela, alebo to spravim pod info@ ?

**Comment by martinmacko47** [comment]
Ok. Skusime to spravit. Vid #322

**Comment by martinmacko47** [comment]
@mmmaly Hotove a mergnute do `master`. Pls pretestuj.

![form](https://user-images.githubusercontent.com/5547275/102610502-98edff00-412d-11eb-9233-61c333aca319.png)

Akurat ma ten google form to dva problemy:
- Kym sa google formular naloaduje, tak podstranka vyzera prazdna. Zobrazit loading indikator pri iframoch vyzera dost komplikovane. To uz by bolo jednoduchsie si ten formular spravit sami.
- Iframe ma fixnu vysku, takze su tam dva vertikalne scrollbary. Jeden nas a jeden z formularu. Neda sa to nijak rozmne vyriesit. Kedze iframe ma iny origin, tak nas skript ani nema ako zistit vysku vnutorneho dokumentu, aby dynamicky upravil vysku iframe. Zmerat to rucne a dat vysku iframe nejakych 2000 pixelov nepomoze, pretoze ten formular meni vysku, ked ho editujes.

**Comment by martinmacko47** [comment]
*label `testing` rusim, stav issue nahradza [stlpec v boarde](https://github.com/martinmacko47/chcemvediet/projects/2#column-12139874)

**Comment by mmmaly** [comment]
Toto mi nefunguje: https://www.chcemvediet.sk:8443/sk/nahlasit-chybajucu-instituciu/
v Safari sa nic nezobrazi, v Chrome mi pise zamracenu tvaricku a hlasku "forms.gle refused to connect."
Pritom, ked pozriem kod a skopirujem URL iframe, konkretne https://forms.gle/pQKEHgAqvNZfF5ue9 tak ide aj v Private mode.

**Comment by mmmaly** [comment]
@viliambalaz neviem, ci pisat sem ci do #322

**Comment by martinmacko47** [comment]
@mmmaly Pozrieme sa na to.

> neviem, ci pisat sem ci do #322

Issues mame rozdelene na epics a tasky. Epics su issues, ktore nam niekto reporte, ze ich treba. Tasky su issues, na ktorych Vilo robi a ku ktorym mu pripravujem podrobne zadania. Tasky su oznacene labelom `issue: task`. Ostatne issues su epics. Cize idealne nefunkcne veci reportovat do non-task issues.

**Comment by martinmacko47** [comment]
@mmmaly Testoval som to na FF aj na Chrome. V oboch to funguje. Aj na localhoste, aj na produckii, aj na `:8443`. Vid screenshot z produkcie:

![chrome](https://user-images.githubusercontent.com/5547275/104914492-831f6400-598f-11eb-85f3-af17962cdb26.png)

Safari este skusim.

Nemas nastavene v browsri nejake paranoidne pluginy a ochranu sukromia? Nieco co by zakazovalo loadnut cross-site iframe a/alebo cross-site skripty? Skus si do virtualky nainstlaovat cistu instalaciu chrome/safari a skus to takto na takej cistej instalacii, aby si mal istotu, ze nemas tam nejake pluginy, co interferuju. Pripadne to este skus na niekoho inom pocitaci.

**Comment by martinmacko47** [comment]
@mmmaly A uz vidim, nefunguje to na mobilnom chrome. Vyriesime.

@viliambalaz Pls otestuj, ci to Tebe na mobilnom chrome funguje a ak nie, skus zistit preco a fixni to.

**Comment by martinmacko47** [comment]
@viliambalaz Vid thread v Slacku, ako to vyriesit

**Comment by martinmacko47** [comment]
@mmmaly Vyzera, ze fixnute. Aspon teda v mobilnom Chrome mi to uz funguje:

![Screenshot_20210125-192332_Chrome](https://user-images.githubusercontent.com/5547275/105748864-fbaf9300-5f42-11eb-9b9e-a1a4ce40340e.jpg)

Skus nasadit a pozri, ci to uz funguje aj v Safari.

**Comment by martinmacko47** [comment]
@mmmaly pisal v maile:
> jo, vyskusane na teste na Macu: Safari, Firefox, Brave / iPhone: Safari
vsade funguje.

Takze issue zatvaram
