### ISSUE TITLE
Nefunkcny login cez niektore socialne siete

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#241]
Nefunguje nam login cez Twitter, LinkedIn a Facebook. Login cez Google funguje.

Skus pozriet `django-allauth` kniznicu, ci v novsej verzii nepublikovali nejake opravy pre Twitter/LinkedIn/Facebook loginy a ak ano, skusit upgradnut, ci to nepomoze.

Pri upgrade pozor, aby sme nemuseli hned upgradovat aj verziu Djanga ci pripadne pythonu, lebo to by sme teraz nezvladli. To budeme musiet postupne. Ak nova verzia `django-allauth` vyzaduje novsie Django alebo novsi python, skusit pozriet poslednu verziu kompatibilnu s nasimi verziami.

- [x] Google - funguje
- [x] Facebook - vyhodene
- [x] Twitter - vyhodene
- [x] LinkedIn - vyhodene

**Comment by martinmacko47** [comment]
Facebook: Zistili sme, ze login funguje, len je disablovana FB app na strane FB. V PR #282 je spisane, ako FB app setupnut. @mmmaly to skusi setupnut na produkcii.

**Comment by viliambalaz** [comment]
`django-allauth` kniznicu nemozeme upgrade-ovat. Od verzie 0.31.0 straca podporu pre nasu verziu `Django 1.7.4` a od verzie 0.22.0 nie su pozivane 'Template context processors' a projekt sa nepodari ani zkompilovat. Od nasej verzie 0.19.1 neboli urobene ziadne zasadne zmeny pre prihlasovanie sa cez Google, Facebook, Twitter, Linkedin.

**Comment by martinmacko47** [comment]
Kedze Twitter a LinkedIn login nam nepouziva skoro nikto, tak asi nema vyznam stracas cas ich upgradovanim. Hlavne, ked je s tym tolko problemov. Twitter a LinkedIn login teda vyhodme. Nechame iba google a FB login.

**Comment by martinmacko47** [comment]
@mmmaly Twitter a LinkedIn loginy sme teda vyhodili. Uz treba len rozbehat ten FB login na produkcii. Priradzujem issue teda uz Tebe.

**Comment by martinmacko47** [comment]
@viliambalaz FB sa nejak brani, kaslime na to, vyhodme ho a nechajme iba google login.
