### ISSUE TITLE
Anonymizovat aj mena priloh

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#254]
Navrhujem anonymizovat aj mena priloh. Stane sa, ze institucia pomenuje prilohu napr. Odpoved - Janko Mrkvicka.pdf, a posle to panovi Mrkvickovi. Meno prilohy vsak zatial zobrazujeme neanonymizovane.

Realny priklad napr na testovacom serveri:
https://www.chcemvediet.sk:8443/sk/infoziadosti/historicke-qr-tabule-3081/

**Comment by mmmaly** [comment]
Doplnim, ze som nasiel aj prilohu s menom Odpoved_Janko_Mrkvicka.pdf (nielen medzery). Idealne pripravit anonyimzaciu aj aby zafungovala v pripade OdpovedJankoMrkvicka.pdf (zatial som nevidel, ale asi sa stane).

**Comment by mmmaly** [comment]
alternativa: pouzime systemove (generovane) meno plus spravna pripona suboru, napr.: T81k44hJB9 + ".pdf" =  T81k44hJB9.pdf

**Comment by martinmacko47** [comment]
@viliambalaz Pls implementuj anonymizovanie nazvov priloh. Nazvy priloh staci zanonymizovat v template pri zobrazovani anonymizovanej ziadosti. Ak si spravne pamatam, v URL nazvy priloh nemame, iba ich ID, takze s URL netreba menit nic, ci?

Nazvy priloh anonymizuj tak, ze zakazane slova mozu byt akykolvek podstring nazvu, nemusia to byt celistve slova. Takze naprikad `FooJankoMrkvickaBar.pdf` to treba zanonymizovat na `FooxxxxxxxxxxBar`. Tj kazdy zakazany podstring sa nadradi anonymizacnym stringom.

Kedze je to bug nad milestonom, ktory je uz v testovacej faze, PR sprav oproti `dev` branchi, nie oproti `master`. Kedze nove features, co mame v `master` este v tomto milestone nereleasujeme.

**Comment by viliambalaz** [comment]
Problem je aj pri URL, ak sa v predmete ziadosti nachadzaju osobne informacie. Taktiez este nie je anonymizacia v zozname vsetkych zverejnenych infoziadosti.

V tomto priklade ostali informacie uzivatela **Philip** a **Kezmarok** nezanonymizovane.
![img](https://user-images.githubusercontent.com/29918752/72902016-0da49780-3d2b-11ea-9b26-7cb8abb4602c.png)

```
>>> ir12.get_absolute_url()
u'/en-us/infoziadosti/affirmation-philip-kezmarok-cc-12/'
>>> ir12.subject
u'Affirmation Philip Kezmarok cc.'

```

**Comment by martinmacko47** [comment]
> Problem je aj pri URL, ak sa v predmete ziadosti nachadzaju osobne informacie. Taktiez este nie je anonymizacia v zozname vsetkych zverejnenych infoziadosti.

@viliambalaz Tento bug sa tyka iba nazvov priloh. Takze tu fixni zatial len tie prilohy. Co s predmetom ziadosti zistim. Diki za postreh.

@mmmaly Treba anonymizovat aj predmet ziadosti? Moc by som necakal, aby ziadatel do predmetu ziadosti pisal svoje osobne udaje. Ci?

**Comment by mmmaly** [comment]
Ani ja. Pre istotu, prebehol som subjecty doterajsich ziadosti a nikto to tak neurobil.

**Comment by martinmacko47** [comment]
@mmmaly @viliambalaz Takze nateraz predmet ziadosti (a teda ani url ziadosti) neanonymizujme. Iba tie nazvy priloh teda.

Ono to aj dava zmysel, nazov prilohy uzivatel ovplyvnit nevie, kedze to pise institucia. Kdezto nazov ziadosti pise on.

**Comment by martinmacko47** [comment]
@mmmaly Fix je mergnuty v `master`. Pls otestuj, ci moze byt.

**Comment by mmmaly** [comment]
The example works properly.
![example](https://user-images.githubusercontent.com/3857547/73615144-b4c7df80-4605-11ea-9193-870e4e6b9ca7.png)

**Comment by mmmaly** [comment]
V ziadosti
https://www.chcemvediet.sk:8443/sk/infoziadosti/vlastnictvo-parcely-c-679-supisne-cislo-81-47/
sa meno prilohy anonymizuje na xxxxx_211_odpoveď.pdf ale po kliknuti sa stiahne aj s menom ziadatela.

**Comment by martinmacko47** [comment]
> V ziadosti
> https://www.chcemvediet.sk:8443/sk/infoziadosti/vlastnictvo-parcely-c-679-supisne-cislo-81-47/
> sa meno prilohy anonymizuje na xxxxx_211_odpoveď.pdf ale po kliknuti sa stiahne aj s menom ziadatela.

@mmmaly Good point. Na to sme zabudli, ze nazov suboru sa posiela aj v hlavickach pri odosielani suboru.

@viliambalaz Pls skus vymysliet ako to zanonymizovat aj v hlavickach v response.

**Comment by martinmacko47** [comment]
@mmmaly Malo by to byt fixnute v `master`. Pls pretestuj.

**Comment by mmmaly** [comment]
Funguje, dakujem.
