### ISSUE TITLE
Wrong mimetype in some jpeg files

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#259]
This type of attachment will generate an error when converting:

![13006650_10153731246414833_7802538303119536023_n](https://user-images.githubusercontent.com/3857547/72919372-a517e380-3d47-11ea-9a66-de38a6680c79.jpg)

`[2020-01-22 18:14:02,447] poleno.cron ERROR Normalizing attachment using imagemagic has failed: <Attachment: 454> An unexpected error occured: CalledProcessError Traceback (most recent call last): File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/anonymization/normalization.py", line 102, in normalize_using_imagemagic check=True, File "/var/www/chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/subprocess32.py", line 426, in run output=stdout, stderr=stderr) CalledProcessError: Command '[u'convert', u'/tmp/tmpASCITU/file.jpe', u'/tmp/tmpASCITU/file.pdf']' returned non-zero exit status 1.

`

**Comment by martinmacko47** [comment]
@mmmaly Pls nauc sa pouzivat "`" a "```" znacky na formatovanie kodu, lebo to sa neda citat

**Comment by martinmacko47** [comment]
@mmmaly Takze ako sme pisali, toto je sposobene nespravnou konfiguraciou ImageMagic. Vid: https://github.com/martinmacko47/chcemvediet#212-imagemagick-configuration

Issue teda zatvaram.
