### ISSUE TITLE
Admin: Zmazanie akcie

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#275]
1. Zakazat hromadne mazanie akcii v zozname akcii `/admin/inforequests/action/` oznacenim niekolkych riadkov a vybranim akcie "Delete selected actions" nad zoznamom. Vygoogli ako sa to robi.

![hromadne](https://user-images.githubusercontent.com/5547275/81392621-38bac780-911f-11ea-866c-36c2923814f4.png)

2. Nechat povolene mazanie akcii po jednej v detailne akcie `/admin/inforequests/action/{ID}/`

![jednotlivo](https://user-images.githubusercontent.com/5547275/81392738-6869cf80-911f-11ea-9666-d7575d5b78ff.png)

Akciu bude mozne zmazat iba ak:

- To nie je akcia typu `REQUEST` alebo `ADVANCED_REQUEST`.
- To nie je jedina akcia v jej branchi

Akcie ktore sa nadaju zmazat, by ani len nemali mat zobrazeny button "Delete".

Proces mazania upravit tak, ze pred zmazanim:

- Ak mazana akcia nie je posledna v historii jej branche, tak upozornit na to. Ale dalsie akcie v historii za nou nemazat.
- Ak v akcii vysia dalsie branche, napriklad ked je akcia postupenie, tak upozornit na to, a prislusne branche zmazat. A rekurzivne ich akcie, maily a branche, atd.
- Ak ma akcia priradene [`InforequestEmail`] typu `applicant-action`, upozornit na to, a zmazat ich.
- Ak ma akcia priradene [`InforequestEmail`] typu `obligee-action`, opytat sa, co s nimi. Ci ich oznacit ako `undecided` alebo `unrelated`. Ak sa oznacia ako `undecided`, tak sa daju opat k dispozicii userovi na opatovne zaradenie. Ak sa oznacia `unrelated`, tak sa uz opatovne nezaradia. (edit: opytat sa netreba, rovno vsetky oznacit za undecided)

[`InforequestEmail`]: https://github.com/martinmacko47/chcemvediet/blob/master/misc/inforequests.md#inforequestemail

Po kliknuti na "Delete" button Django zobrazi "Are you sure?" obrazovku. Idealne vsetky tieto veci spravit, tak aby boli sucastou "Are you sure?" obrazovky. Teda, aby sa tam vypisal zoznam, co vsetko sa ide zmazat. A vsetky dalsie upozornenia a otazky.

![areyousure](https://user-images.githubusercontent.com/5547275/81394187-d911eb80-9121-11ea-8fe8-a7031ba61cb6.png)

**Comment by viliambalaz** [comment]
Kazda branch bude mat minimalne 2 akcie. Prva akcia musi byt vzdy typu `REQUEST` alebo `ADVANCED_REQUEST`. Cize podmieka  pre zmazanie akcii **To nie je jedina akcia v jej branchi** je nepotrebna a je osetrena uz prvou podmienkou.

**Comment by martinmacko47** [comment]
> Kazda branch bude mat minimalne 2 akcie. Prva akcia musi byt vzdy typu `REQUEST` alebo `ADVANCED_REQUEST`. Cize podmieka  pre zmazanie akcii **To nie je jedina akcia v jej branchi** je nepotrebna a je osetrena uz prvou podmienkou. 

To je sice pravda, ale ak nejakym omylom nam niekedy niekde vznikne brancha, ktora nema v sebe `REQUEST` alebo `ADVANCED_REQUEST`, tak aby po zmazani poslednej akcie neostala brancha prazdna. Nemalo by to nastavat, ale pre istotu radsej to mat osetrebe.
