### ISSUE TITLE
translate deadline information in request detail

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#30]
e.g. Effective Date: Feb. 19, 2015 — Deadline: 15 WD, 15 WD remains

**Comment by martinmacko47** [comment]
Added templates for deadline text:
 - /chcemvediet/apps/inforequests/templates/inforequests/texts/detail-action-deadline.{en,sk}.html

**Comment by martinmacko47** [comment]
translations to english are postponed to later
