### ISSUE TITLE
invites: missing port in the invite url

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#31]
When an invite is sent, the port is missing. So, if the server is running at localhost:8000, the user obtains only 
http://localhost/en/invitations/accept/izhxitvkt3en0mura29vc9wb8alz34fwuu6av9abl0qbxw2zzmpaqwbrsmpab0r7/
which does not work.

**Comment by martinmacko47** [comment]
You need to configure your domain with setup.py:
```
Server domain (with www if used) [www.chcemvediet.sk]: localhost:8000
```

**Comment by malymichal** [comment]
it works.
