### ISSUE TITLE
Formular na pridanie institucie

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#322]
Vygoogli ako sa da inline na web pridat google formular. Bud ako iframe, alebo nejakym podobnym mechanizmom, ako mame pridany webe google search.

Potom sprav novu page na pridanie novej institucie s routou `/sk/pridat-instituciu/`, a na tej pagi pouzi google form https://forms.gle/pQKEHgAqvNZfF5ue9

Linku na vytvorenu page pridaj do praveho menu:

![menu](https://user-images.githubusercontent.com/5547275/97917924-8a05e580-1d55-11eb-97c0-548fe074d629.png)

**Comment by mmmaly** [comment]
vid #236
