### ISSUE TITLE
Implementovat reCaptcha

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#341]
Objavuju sa nam spamove registracie, coho dosledkom je, ze rozposielame spamove potvrdzovacie maily. Na registracny a prihlasovaci formular treba preto pridat captchu. Skusme google reCaptcha.

Vygoogli, ci nie je pre to rovno nejaka hotova django kniznica. Aby stacilo do django formulara pridat captcha field (alebo nieco take) a vsetko bude fungovat ako ma. Ak nic take neexistuje, skusime vymysliet, ako to spravit.

Pri registracii, ak je captcha neuspesna, tak user by sa v DB nemal ani len vytvorit. Urcite sa vsak takemu spam userovi nesmie posielat ziaden potvrdzovaci mail.

Pri prihlaseni, ak je captcha neuspesna, tak sa userovi prihlasit nepodari. Rozhodnutie, ci je captcha uspesna alebo nie by malo nastat este predtym, nez sa kontroluje zadane login/heslo. To preto, aby nahodou utocnik nevedel nejak stale vydedukovat, ci zadany login/heslo je platne.

**Comment by martinmacko47** [comment]
@mmmaly Mergnute. Pls pretestuj, ci captcha funguje podla ocakavani. Nezabudni spustit `setup.py` a zadat credentials pre captchu. Precitaj si [README](https://github.com/martinmacko47/chcemvediet/blob/master/README.md#5-google-recaptcha-engine-key) ako captchu nakonfigurovat.

**Comment by malymichal** [comment]
dakujem, nakonfigurovane a funguje.

**Comment by mmmaly** [comment]
Dakujem, nakonfigurovane a funguje.
