### ISSUE TITLE
Aktualizovat prevadzkovatela portalu

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#346]
Na obrazovkach:
 - https://www.chcemvediet.sk/sk/ochrana-osobnych-udajov/
 - https://www.chcemvediet.sk/sk/podmienky-pouzivania/

Nahrad:

> Inštitút pre dobre spravovanú spoločnosť, občianske združenie so sídlom a adresou pre doručovanie Štúrova 3, 811 02 Bratislava, Slovenská republika, IČO: 36070629, zapísaná v registri občianskych združení vedenom Ministerstvom vnútra SR

za:

> Chcemvediet.sk, občianske združenie so sídlom a adresou pre doručovanie Karpatské námestie 7770/10A, 831 06 Bratislava, Slovenská republika, IČO: 50436376, zapísané v registri občianskych združení vedenom Ministerstvom vnútra SR

Prejdi celu codebase a pozri, kde sa spomina "Inštitút pre dobre spravovanú spoločnosť" resp. "SGI". Ak sa spomina ako prevadzkovatel, nahrad ho s "Chcemvediet.sk, občianske združenie" resp. "Chcemvediet.sk, o. z.". Ak sa spomina ako partner, v spolupraci s, a podobne, tak to nechaj nezmenene.

Do komentara tu v issue potom napis, kde vsade "Inštitút pre dobre spravovanú spoločnosť" resp. "SGI" ostal uvedeny.

**Comment by viliambalaz** [comment]
Jediný odkaz na "inštitút pre dobre spravovanú spoločnosť" ostal v [o-projekte](https://github.com/martinmacko47/chcemvediet/blob/master/media/pages/sk/o-projekte/page.html#L71).

**Comment by martinmacko47** [comment]
> Jediný odkaz na "inštitút pre dobre spravovanú spoločnosť" ostal v [o-projekte](https://github.com/martinmacko47/chcemvediet/blob/master/media/pages/sk/o-projekte/page.html#L71).

@viliambalaz Ok. Tak je ten odkaz spravne, kedze je to spominane ako "v spolupraci".
