### ISSUE TITLE
Nedokoncena veta vo FAQ

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#352]
Vo [FAQ](https://www.chcemvediet.sk/sk/faq/#moze-mi-institucia-odmietnut-poskytnut-informacie) je nedokoncena veta:

![faq](https://user-images.githubusercontent.com/5547275/106508006-21511500-64cc-11eb-8a46-5298cbab3fc5.png)

Veta je tam nedokoncena uz od cias, kedy [Maja tie FAQ pisala](https://github.com/martinmacko47/chcemvediet/commit/65f518f24239c5eec78e184ee6b82e9b64cd126a#diff-d4d32166fea7b89364bc7c419ef0186686aa993ba47a38fb8499f5df3f5315bd).

**Comment by martinmacko47** [comment]
@mmmaly Netusis co tam Maja chcela napisat? Pripadne ako jednoduchy fix mozeme tu poslednu nedokoncenu vetu vyhodit.

**Comment by mmmaly** [comment]
...nemalo podliehať utajeniu.

**Comment by martinmacko47** [comment]
> ...nemalo podliehať utajeniu.

@viliambalaz pls dopln
