### ISSUE TITLE
Neprihlaseny uzivatel dostane 404, ked klikne na link z notifikacneho emailu

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#358]
Uzivatel dostane notifikaciu napr. mate novy email pre ziadost https://www.chcemvediet.sk/sk/infoziadosti/stavby-v-lokalite-botanicka-zahrada-stupava-4737/ 
Ak vsak nie je prihlaseny, linka ho zavedie na 404. Nepresmerovat ho radsej na login?

(Toto sa tyka iba nezverejnenych ziadosti - pre zverejnene ho zavedie na anonymizovanu stranku, to je asi ok; to sa aj tak skoro nikdy nestane, lebo aby bola zverejnena, musi byt ukoncena, takze k nej nebudu nove emaily a notifikacie).

**Comment by martinmacko47** [comment]
@mmmaly ano, je to bug. Asi najlahsie to bude fixnut tak, ze sa posle linka https://www.chcemvediet.sk/sk/accounts/login/?next=/sk/infoziadosti/stavby-v-lokalite-botanicka-zahrada-stupava-4737/

To znamena, ze ak je user nie je prihlaseny, zobrazi sa mu login a po prihlaseni ho to redirectne. Ak uz je prihlaseny, tak ho to redirectne rovno. Ak je prihlaseny ako niekto iny, tak ho to najprv redirectne a potom ukaze 404.

Uplne nechceme aby povodna linka automaticky presmerovala na login, pretoze takto by sme verejne odhalili, ze dana infoziadost existuje, len nie je zverejnena. Co nie je dobra prax.



@viliambalaz Pls skus upravit linky v notifikaciach, co rozposielame, tak aby sli redirectom cez login. Pozri celu codebase, kde ake linky posielame v notifikacnych mailoch a uprav to vsade, kde su linky na nieco neverejne.

**Comment by martinmacko47** [comment]
@mmmaly Fixnute a mergnute. Pls pretestuj.

**Comment by mmmaly** [comment]
Redirect sa posiela v maili a funguje. mozeme zavriet.
