### ISSUE TITLE
Refusal appeal properly sanitized step text

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#37]
Add text to refusal appeal properly sanitized step.

Search FIXME in:
 * chcemvediet/apps/inforequests/templates/inforequests/appeals/texts/refusal/sanitization_properly_sanitized.html

**Comment by mmmaly** [comment]
e.g. example in Slovak

Odvolanie voči rozhodnutiu o nesprístupnení informácie
Začiernenie citlivých informácií

Označili ste, že inštitúcia citlivé informácie vyčiernila korektne.
FIXME Cele zle, nezdovodnene dovody: utajovaná skutočnosť.

needs more info for user why we cannot continue.
