### ISSUE TITLE
Vyrocne spravy

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#393]
Na page `/podporte-nas/` pridat novsie vyrocne spravy.

**Comment by martinmacko47** [comment]
@mmmaly Pls uploadni sem pdfka, nech ich tam pridame. Alebo sprav rovno PR.

**Comment by mmmaly** [comment]
https://drive.google.com/drive/folders/1_-eZiMBFllSlv-mrt9ZbOR9jttHErdPC

**Comment by martinmacko47** [comment]
@viliambalaz Pouzi vyrocne spravy z linku vyssie. Pristup by si mal mat na Tvoj gmail account.
