### ISSUE TITLE
Forbid inforequests to obligees with no email

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#62]

**Comment by martinmacko47** [comment]
Vyzera, ze pokus podat ziadot institucii bez emailu dopadne takto:
```
[2015-12-11 12:54:24,868] django.request ERROR Internal Server Error: /sk/infoziadosti/nova-ziadost/
Traceback (most recent call last):
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/allauth/account/decorators.py", line 33, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/views/inforequest.py", line 83, in inforequest_create
    inforequest.main_branch.last_action.send_by_email()
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/action.py", line 494, in send_by_email
    email=msg.instance,
AttributeError: 'EmailMessage' object has no attribute 'instance'
```

**Comment by martinmacko47** [comment]
@mmmaly pls na branchi "no-email-obligees" otestuj, ze:
- [ ] ziadost sa neda podat institucii bez emailu
- [ ] ziadost sa da podat institucii s emailom
- [ ] ziadost sa da postupit institucii bez emailu
- [ ] ak ziadost bola postupena institucii bez emailu a tato nova institucia poslala vyzvu na doplnenie ziadosti postou, tak doplnenie nejde poslat, lebo nevieme kam
- [ ] ak ziadost bola postupena institucii bez emailu a tato nova institucia poslala vyzvu na doplnenie ziadosti emailom, tak doplnenie ide poslat a posle sa na email, odkial prisla vyzva
- [ ] zamysli sa, na aky pripad som este zabudol

Co by sme mali vlastne spravit, ak sa ziadost postupi institucii bez emailu? User sa moze takto lahko zaseknut a nemat ako odpovedat.

**Comment by mmmaly** [comment]
vetva no-email-obligees konci s chybou, robene v uplne cistom adresari:

 mkdir ch123
 cd ch123
 git clone git@github.com:martinmacko47/chcemvediet.git
 cd chcemvediet/
 python setup.py 

Server mode []: 1
Install requirements for unittesting? Y/N [N]: n (skusal som aj Y)
Server domain (with www and/or port number if used, eg. localhost:8000) [www.chcemvediet.sk]: localhost:8000
Admin e-mail [admin@localhost]: 
Inforequest unique e-mail [{token}@mail.localhost]: 
Default from e-mail [info@localhost]: 
Obligee dummy e-mail []: mail@{name}.example.com
Traceback (most recent call last):
  File "setup.py", line 599, in <module>
    main()
  File "setup.py", line 575, in main
    configure_cache(configure, settings)
  File "setup.py", line 365, in configure_cache
    default_prefix = slugify(configure.get(u'server_domain'))
  File "setup.py", line 25, in slugify
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore')
TypeError: must be unicode, not str
Traceback (most recent call last):
  File "setup.py", line 599, in <module>
    main()
  File "setup.py", line 559, in main
    call(u'Rerunning with: env/bin/python', [u'env/bin/python', u'setup.py']);
  File "setup.py", line 36, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/python', u'setup.py']' returned non-zero exit status 1

**Comment by martinmacko47** [comment]
Fixnute. Btw, chyba tam bola uz od 6. decembra, taze bola vo vsetkych vetvach. Vsade mergnute. (pozri si graf branchi:-)

**Comment by mmmaly** [comment]
fix funguje, idem testovat.

**Comment by malymichal** [comment]
- [x] ziadost sa neda podat institucii bez emailu
- [x] ziadost sa da podat institucii s emailom
- [x]   ziadost sa da postupit institucii bez emailu
- [x] ak ziadost bola postupena institucii bez emailu a tato nova institucia poslala vyzvu na doplnenie ziadosti postou, tak doplnenie nejde poslat, lebo nevieme kam
- [x] ak ziadost bola postupena 2 instituciam, prvej bez emailu a druhej s emailom:
- [x]  ... druhej ide poslat
- [x]  ... prvej nejde poslat.
- [x] da sa ulozit  draft bez uplne vyplnenej institucie.
-  neda sa ulozit draft ziadosti, ak je v nom institucia bez emailu. 
- (?) ak ziadost bola postupena institucii bez emailu a tato nova institucia poslala vyzvu na doplnenie ziadosti emailom, tak doplnenie ide poslat a posle sa na email, odkial prisla vyzva (zvolil som si dummy, musim najprv prist na to, ako to otestovat)

**Comment by martinmacko47** [comment]
(?) skus otestovat na dev sevri (chv2 na poleno.sk), kde sa maily posielaju na dummy adresy. Instituciu bez emailu si zedituj rucne cez admin rozhranie a potom rucne posli mail na adresu ziadosti odniekial z testovaceho mailu.

**Comment by mmmaly** [comment]
otestovane, funguje:
- [x] ak ziadost bola postupena institucii bez emailu a tato nova institucia poslala vyzvu na doplnenie ziadosti emailom, tak doplnenie ide poslat a posle sa na email, odkial prisla vyzva

**Comment by mmmaly** [comment]
s tym draftom by som teraz neriesil, nech tie vetvy mergneme, spravim separatne issue.

**Comment by martinmacko47** [comment]
Podobne ako v #112, pls nezatvaraj, kym nie je deploynute.

**Comment by mmmaly** [comment]
ok. Ano, mozes mergnut.

**Comment by martinmacko47** [comment]
Mergnute, mozes deploynut. Pred deployom to pre istotu aspon trochu otestuj aj na testovacej kopii produkcneho servra.

Btw, pozor, v deploy branchi su uz vsetky tri branche.

**Comment by mmmaly** [comment]
nasadene na prod (#62 #112 #128)
