### ISSUE TITLE
FAQ page design

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#67]
http://www.chcemvediet2.labs.poleno.sk/sk/faq/

**Comment by lpk90901** [comment]
Tu su navrhy uprav:
(vseobecne pre *vsetky textove* stranky tohto druhu / template kde je text + sidedbar widget)

1) **SIRKA TEXTU** 
Vidim ze template je iny nez boli nahlady, a verim ze to bude mat nejaky dobry dovod.
Kazdopadne pri takychto textovych strankach a zvolenej velkosti pisma je riadok prilis dlhy a tazko sa cita. Takze bolo by super bud zuzit content area alebo zvacsit font = **globalne pre takyto typ podstranok** 

[hore aktualna verzia, dole novy navrh]
![sirka-textu](https://cloud.githubusercontent.com/assets/6820342/12208208/bdbe4d5c-b64b-11e5-80c4-5c878d007a10.png)

2) **Zrusit text-align JUSTIFY pri odstavcoch textu** - zarovnavajme text **len dolava**, nie do bloku, nedelime slova a v textoch nam vynikaju "rieky"

3) **line height zmenit vsade kde je tato velkost pisma na 23px**

[vlavo aktualna verzia, vpravo novy navrh]
![new-line-height-23px](https://cloud.githubusercontent.com/assets/6820342/12208219/d2137e9e-b64b-11e5-9ce8-6374fe3dd668.png)

4) **Riesenie pre FAQ**: accordion + -
Kedze otazky budu pribudat, potrebujeme ich skratit a nezobrazovat s odpovedami.
Sidebar ma takmer rovnaky styling ako widget v #72 - ak chces vypusti aj >

![faq_desktop](https://cloud.githubusercontent.com/assets/6820342/12208284/4178b650-b64c-11e5-8ff4-09b394f569a0.png)
![fag_mobile](https://cloud.githubusercontent.com/assets/6820342/12208291/4719a646-b64c-11e5-8a1c-d2c66a60f5dd.png)

**Comment by martinmacko47** [comment]
Zapracovane v ramci #337
