### ISSUE TITLE
Article references design

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#68]
http://www.chcemvediet2.labs.poleno.sk/sk/pravne-predpisy/
http://www.chcemvediet2.labs.poleno.sk/sk/pripadove-studie/

![a](https://cloud.githubusercontent.com/assets/5547275/11045488/14a75df0-8728-11e5-9687-e65d927f1836.png)

**Comment by lpk90901** [comment]
- [ ] 2px seda linka #cccccc nad textom
- [ ] font-size: 12px;
- [ ] line-height: 20px;
- [ ] mierne odsadenie

Nahlad:
<img width="299" alt="screen shot 2016-01-08 at 21 25 58" src="https://cloud.githubusercontent.com/assets/6820342/12208964/67d73bec-b650-11e5-81d5-1384960f58ac.png">

**Comment by lpk90901** [comment]
OK, dajme ich v obidvoch pripadoch
**na pravu stranu**
**bez sipiek** [ktore boli v #68 ]

**Comment by martinmacko47** [comment]
Zapracovane v ramci #337
