### ISSUE TITLE
Login page design

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#69]
http://www.chcemvediet2.labs.poleno.sk/sk/accounts/login/

Note: Visually emphasize a link/button to sign up if not registered yet.

**Comment by lpk90901** [comment]
Navrhuje skratit text nad formularom:
Prihláste sa do existujúceho účtu, cez sociálnu sieť alebo sa **registujte**.

Inak minimalne vizualne zmeny:

![login_mobile](https://cloud.githubusercontent.com/assets/6820342/12203212/12badb86-b62e-11e5-91ec-89d8f8d69cfa.png)
![login-desktop](https://cloud.githubusercontent.com/assets/6820342/12203213/12c0023c-b62e-11e5-9efd-cff48582e8b4.png)

**Comment by martinmacko47** [comment]
@JakubKmet, pls, zamysli sa, ci takto by boli texty ok. Pripadne na mobile a na desktope mozu byt texty rozne.

@lpk90901 tlacitko "Prihlasi sa" si tu zarovnala do stredu. V ostatnych formularoch okrem hlavnej stranky mame tlacitka zarovnane do lava.

**Comment by JakubKmet** [comment]
Text je v porovnaní so starším jednoduchší a jasnejší. Doplnil som ho na drive.
