### ISSUE TITLE
Visualize undefined subject/obligee in draft list

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#73]
http://www.chcemvediet2.labs.poleno.sk/sk/infoziadosti/

![a](https://cloud.githubusercontent.com/assets/5547275/11169054/6132efaa-8baa-11e5-952a-08c8ef3e2817.png)

**Comment by lpk90901** [comment]
Zatvorky su standard napr. aj v gmaily.
Skratila by som text:

(Bez predmetu) + (Žiadna inštitúcia)
(No subject) + (No institution)

Ak by sa dala pouzit svetlejsia šedá farba textu, pomohlo by to, ze by to vyzeralo viac "missing" = ale chapem ze to moze zbytocne komplikovat veci.

Ak sa nedá zmeniť farba, skráťme text.
