### ISSUE TITLE
Specify inforequest list date & activity values

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#74]
Specify how **exactly** is last inforequest activity defined. Pending/missed deadline vs. last action vs. possible next action, etc. Define what is the last inforequest activity for advanced inforequests.

Also define **exactly** which dates should be displayed for which activities.

http://www.chcemvediet2.labs.poleno.sk/sk/infoziadosti/

![a](https://cloud.githubusercontent.com/assets/5547275/11169077/53767a98-8bab-11e5-973b-6ad85ee2d0ff.png)

**Comment by mmmaly** [comment]
Missed deadline or last action by user or institution or arrived email, whichever is newer.
I think this is the same for all 3 sets.
If there is a pending deadline for the user, show Waiting for the user input ("Čaká sa na Vás"). If there is a pending deadline for the instution, show Waiting for the instutution - "Čaká sa na inštitúciu", both along with the date of last action.

**Comment by martinmacko47** [comment]
Okrem Full disclosure, Affirmation a Reversion sa vzdy caka bud na usera alebo na instituciu. Takze vzdy by sa pisalo bud "Čaká sa na Vás/instituciu" alebo "zmeskana lehota". A nikdy by sa nepisala "last action by user or institution", co je zjavne zle.

Pls, zober si diagram https://github.com/martinmacko47/chcemvediet/blob/master/misc/inforequest-flow.odg a pre kazdy stav sa zamysli a napis, co sa ma po nom vypisat. Zakazdym obe moznosti pred a po vyprsani lehoty. Pretoze to co si napisal sice vyzera pekne, ale ked sa nad tym zamyslis, tak to v mnohych pripadoch nie je to, co by clovek ocakaval. 

To by bolo pre nepostupene ziadosti. Co so ziadostami, ktore su postupene a maju viacej vetiev?

**Comment by mmmaly** [comment]
0. Ak je k aspon jednej vetve prijaty nerozhodnuty mail, tak napisat: Nový čakajúci email - prosím, rozhodnite
*pre nerozvetvene ziadosti, ktoré nemajú čakajúci email*
1. Clarif Req.
 * (v uz. lehote):  "Inštitúcia vyžaduje doplnenie, čaká sa na Vašu odpoveď." (zobrazit v: Podané) [Urgentnost: 1]
 * (po uz. lehote)  "Inštitúcia vyžadovala doplnenie, neodpovedali ste v lehote." (zobrazit v: Neuspesne) [Urgentnost: 3]
2. Expiration
 * (v uzivatelovej lehote): "Žiadosť podaná/postúpená//Vec vrátená na ďalšie konanie, [nová] inštitúcia neodpovedala v lehote, máte možnosť podať odvolanie." (zobrazit v: Podané). *Cize konkretne po bodoch:*
   * po Request-e: "Žiadosť podaná, inštitúcia neodpovedala v lehote, máte možnosť podať odvolanie." (zobrazit v: Podané). [Urgentnost: 2]
    * po Clarif Resp.-e: "Doplnili ste podanie, ale inštitúcia ďalej nereagovala v lehote, máte možnosť podať odvolanie." (zobrazit v: Podané). [Urgentnost: 2]
     * po Advancement-e: "Žiadosť postúpená, nová inštitúcia neodpovedala v lehote, máte možnosť podať odvolanie." (zobrazit v: Podané). [Urgentnost: 2]
    * po Remandment-e: "Vec vrátená na ďalšie konanie, inštitúcia neodpovedala v lehote, máte možnosť podať odvolanie." (zobrazit v: Podané). [Urgentnost: 2]
 * (po uzivatelovej lehote) "Inštitúcia neodpovedala v lehote, nepodali ste odvolanie v lehote." (zobrazit v: Neúspešné) [Urgentnost: 3]
3. Appeal expiration:  "O odvolaní nebolo rozhodnuté v lehote. Môžete sa už len súdiť. " (zobrazit v: Neúspešné) [Urgentnost: 3]
1. Request/Advanced (ak i. plynie lehota): "Žiadosť podaná/postúpená, inštitúcii plynie lehota." (zobrazit v: Podané) [Urgentnost: 3]
4. Clarif Resp.
 * (v i. lehote):  "Doplnili ste podanie,  inštitúcii plynie lehota." (zobrazit v: Podané) [Urgentnost: 3]
 * (po i. lehote)  vid bod Expiration
5. Extension: "Inštitúcia si predĺžila lehotu a táto lehota jej ešte plynie." (zobrazit v: Podané) [Urgentnost: 3]
6. Full Disclosure: "Plné sprístupnenie" (zobrazit v: Zodpovedane) [Urgentnost: 3]
7. Non-full Discl. 
 * None
   * (v uzivatelovej lehote):  "Inštitúcia nesprístupnila informácie, máte možnosť podať odvolanie." (zobrazit v: Podané) [Urgentnost: 2]
    * (po uz. lehote)  "Inštitúcia nesprístupnila informácie, nepodali ste odvolanie v lehote." (zobrazit v: Neuspesne) [Urgentnost: 3]
 * Partial
   * (v uzivatelovej lehote):  "Inštitúcia sprístupnila informácie len čiastočne, máte možnosť podať odvolanie." (zobrazit v: Podané) [Urgentnost: 2]
    * (po uz. lehote)  "Inštitúcia sprístupnila informácie len čiastočne, nepodali ste odvolanie v lehote." (zobrazit v: Neuspesne) [Urgentnost: 3]
8. Refusal
 * None
   * (v uzivatelovej lehote):  "Inštitúcia rozhodla o nesprístupnení informácie, máte možnosť podať odvolanie." (zobrazit v: Podané) [Urgentnost: 2]
    * (po uz. lehote)  "Inštitúcia rozhodla o nesprístupnení, nepodali ste odvolanie v lehote." (zobrazit v: Neuspesne) [Urgentnost: 3]
 * Partial
   * (v uzivatelovej lehote):  "Inštitúcia rozhodla, že  informácie sprístupní len čiastočne, máte možnosť podať odvolanie." (zobrazit v: Podané) [Urgentnost: 2]
    * (po uz. lehote)  "Inštitúcia rozhodla, že  informácie sprístupní len čiastočne, nepodali ste odvolanie v lehote." (zobrazit v: Neuspesne) [Urgentnost: 3]
9. Remandment
 * (v i. lehote): "Nadradený orgán vrátil vec na nové konanie. Inštitúcii plynie lehota." (zobrazit v: Podane) [Urgentnost: 3]
 * (po i. lehote): to co je v Expiration pre Remandment (zobrazit v: Podane)
10. Affirmation: "Nadradený orgán potvrdil pôvodné rozhodnutie. Môžete sa už len súdiť. " (zobrazit v: Neuspesne) [Urgentnost: 3]
11. Reversion: 
 * Full: "Nadradený orgán zmenil pôvodné rozhodnutie a všetky informácie sprístupnil." (zobrazit v: Zodpovedane) [Urgentnost: 3]
  * Partial: "Nadradený orgán zmenil pôvodné rozhodnutie, ale niektoré informácie stále nesprístupnil. Môžete sa už len súdiť. " ( zobrazit v: Neuspesne, *hoci si viem predstavit, ze i ciastocny uspech moze byt v podstate uspech, ale triedme to pre poriadok takto*) [Urgentnost: 3]
  * None: "Nadradený orgán zmenil pôvodné rozhodnutie, ale žiadne informácie nesprístupnil. Môžete sa už len súdiť. " ( zobrazit v: Neuspesne.) [Urgentnost: 3] *Aj tento pripad sme mali, vsak? Napr. odvolaci organ rozhodne, ze dovody v odvolani uzivatela su spravne, ale stale kvoli niecomu nemozno info spristupnit, napriklad, ze info neexistuje* 
*pre rozvetvene ziadosti, ktoré nemajú čakajúci email v ziadnej vetve*
14. Zoradit podla "urgentnosti" vstupu pouzivatela: 1. Čaká sa na Vás. 2. Máte možnosť podať odvolanie 3. iné. V rámci tej istej triedy urgentnosti zobraziť najnovšiu akciu. Čiže:
 * ak je niektora vetva v Clarif Req. v uzivatelskej lehote (kde urg=1), zobrazit prislusny text " "Inštitúcia vyžaduje doplnenie, čaká sa na Vašu odpoveď." (zobrazit v: Podané)
  * inak, ak je niektora vetva v moznosti, ktora umoznuje podat odvolanie (urg=2), zobrazit prislusny text (ak je viac vetiev, tak casovo poslednu z nich) (zobrazit v: Podané)
  * inak zobrazit text k akcii, ktora bola posledna (s najnovsim datumom). Ak su vsetky vetvy Neuspesne podla hore uvedeneho k single, tak zobrazit v Neuspesne, inak zobrazit Podané.

Ak sa ti nechce posledny bod riesit hned, tak kludne zatial zobraz: Rozvetvená žiadosť, kliknite pre detaily.

**Comment by mmmaly** [comment]
dohodnute, ze popis hore sa da skratit tak, ze bude:
1 brancha - datum najnovsej akcie a meno + plynie (vam/institucii) lehota (po klikuti ? = datum)
2+ branche - to iste, ale pre najnovsiu akciu
