### ISSUE TITLE
Specify how to sort out inforequests into tables

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#75]
We have three tables: Submitted, Answered and Failed. How to decide which inforequest belongs to which table?

http://www.chcemvediet2.labs.poleno.sk/sk/infoziadosti/

![a](https://cloud.githubusercontent.com/assets/5547275/11169089/43167bca-8bac-11e5-8476-7e34f024ff6d.png)

**Comment by mmmaly** [comment]
Submitted are those which are in progress, i.e. there is a further action possible by user or by the institution.
Failed are those where no information was provided or where the deadline was missed by the user.
Answered are those where no action was possible and at least some information was provided (even partially refused, example above should read: "týkajúce sa tendra na stavbu nového štadiónu - Čiastočné zamietnutie") and user did not miss the deadline.

**Comment by martinmacko47** [comment]
Odlozene kym sa vyriesi: #74

**Comment by martinmacko47** [comment]
Vyriesene v #249
