### ISSUE TITLE
inforequest index panel icons

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#77]
Should we use fontawesome icons or custom icons here? If custom, please draw distinct icons for email vs. smail and a new icon for archive. If fontawesome icons, please select an icon for archive.

![a](https://cloud.githubusercontent.com/assets/5547275/11177445/f0714cf2-8c45-11e5-9ed2-a3fa1752f721.png)
![b](https://cloud.githubusercontent.com/assets/5547275/11177446/f0a35ecc-8c45-11e5-9543-a662a0e2afd9.png)

**Comment by lpk90901** [comment]
archiv ziadosti 
dajme = name: doc-inv (doc, file, article)
