### ISSUE TITLE
inforequests index panels for new user

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#78]
what to show instead of "I've got a new smail" panel if the user has no pending inforequests yet?
![a](https://cloud.githubusercontent.com/assets/5547275/11177700/b30c0a76-8c47-11e5-9e42-50d54f47be16.png)

**Comment by mmmaly** [comment]
Nothing would look bad, wouldn't it?

Show alternative text, in Slovak: 

*Spracujeme aj odpoveď poštou*
Ak Vám príde odpoveď od inštitúcie poštou, tu ju budete môcť nahrať, aby aj ostatní užívatelia mali informácie k dispozícii. Zároveň Vám pomôžeme odpoveď zatriediť a podľa potreby podniknúť ďalšie akcie.
