### ISSUE TITLE
obligee unique name

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#81]
Shouldn't obligee unique name have a comma between its official name and the suffix? Eg. "Centrum voľného času, Bratislava-Petržalka, Pankúchova 4" instead of "Centrum voľného času Bratislava-Petržalka, Pankúchova 4". It looks strange now.

![a](https://cloud.githubusercontent.com/assets/5547275/11304518/ae3fb6f0-8fa8-11e5-808d-b102e1c1cf9f.png)

**Comment by mmmaly** [comment]
It is not so clear but I agree it looks better. I found some counterexamples, e.g. www.gjh.sk,  www.gmet.sk, zspankuchova.stranka.info use the form without comma in their logos or less official statements, but in official documents they separate always with a comma.
I will modify obligee list appropriately.

**Comment by mmmaly** [comment]
Updatol som, okrem toho par dalsich drobnych fixov.
