### ISSUE TITLE
Multisize favicon .png

### ISSUE THREAD

**Issue by lpk90901** [martinmacko47/chcemvediet#88]

**Comment by lpk90901** [comment]
Vyrobila som mutisize favicon (pre retinu a spol)
v tomto http://www.xiconeditor.com/

ale posielam aj PNG 16x16:
https://www.dropbox.com/s/nr409sfropem6jp/favicon.zip?dl=0

![favicon_16x16](https://cloud.githubusercontent.com/assets/6820342/11501537/434476f2-9835-11e5-8c63-58f0f60a2f55.png)

**Comment by martinmacko47** [comment]
ikonka je v /static/favicon.ico
Miso, pls, sprav staticky alias na /favicon.ico

**Comment by mmmaly** [comment]
pullnute, collectnute, aliasnute. Funguje mi v Safari, FF, Chrome, IE.

**Comment by martinmacko47** [comment]
Zaujimave, ze mne to vo FF ikonku nezobrazilo. Asi pridam aj <meta> tag do html.

**Comment by mmmaly** [comment]
treba tusim pockat alebo umazat cache.

**Comment by martinmacko47** [comment]
nepomohlo, ale na testovacich virtualkach to fungovalo vo vsetkych browsroch, co mam, tak asi len hlavny firefox to ma zacacheovane az prilis.
