### ISSUE TITLE
Http error pages (400, 403, 404, 500)

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#89]
urobit, ze sa spravi error page, nie prazdna stranka
 - [x] 400 Bad Request (SuspiciousOperation)
 - [x] 403 Forbidden (PermissionDenied)
 - [x] 404 Not Found
 - [x] 500 Server Error
 - [x] obsah chybovych stranok
 - [x] text na chybovych strankach

**Comment by martinmacko47** [comment]
Na http://www.chcemvediet.labs.poleno.sk/ by custom error stranky mali fungovat. Na chcemvediet2 nefunguju, lebo tam mame zapnuty debug. @mmmaly pls otestuj aspon 404 teraz na labs. Ostatne chyby sa Ti asi na labs nejak jednoducho vyrobit nepodaria. Tie otestujes potom pred deployom.

Co by mali chybove hlasky obsahovat?

**Comment by mmmaly** [comment]
funguje, cize mozeme nahodit.

- 400: Nesprávna požiadavka. Došlo pravepodobne k chybe pri spracovaní. Napíšte nám na webmaster@chcemvediet.sk.
- 404: Stránka neexistuje. Ak si myslíte, že by mala, napíšte nám na webmaster@chcemvediet.sk.
- 403: Nepovolený prístup. Pravdepodobne sa pokúšate pristúpiť k interným súborom, ktoré nie sú verejné. Ak si myslíte, že ide o chybu, napíšte nám na webmaster@chcemvediet.sk.
- 500: Chyba servera. Došlo k chybe pri spracovaní. Napíšte nám prosím, čo sa stalo, čo ste robili pred tým, ako sa chyba vyskytla, na webmaster@chcemvediet.sk.

![screen shot 2015-12-10 at 11 16 56](https://cloud.githubusercontent.com/assets/3857547/11712796/96246c1e-9f2f-11e5-8f72-b321e23f19e0.png)

**Comment by martinmacko47** [comment]
Texty som upravil a vetvu som mergol do deploy. Pred pustenim na zivy server, pls, oskusaj, ze aj ostatne chyby funguju. 500 dosiahnes zavedenim chyby do kodu. 400 dosiahnes tak, ze submitnes formular bez csrf tokenu. 403 asi spravis iba tak, ze niekde do kodu pridas ``raise PermissionDenied()``.

**Comment by martinmacko47** [comment]
@mmmaly toto si uz deployol? lebo v #123 user reportoval nieco a poslal screenshot 403 chyby. To co poslal vsak nie je nas template, ale nejaky fallback Django template, ktory by sa nemal nikdy zobrazovat.
![x](https://cloud.githubusercontent.com/assets/5547275/11897219/27a1c0f6-a58e-11e5-94cb-266e0678d59b.png)

**Comment by malymichal** [comment]
ano deoployol v pondelok spolu s ostatnymi, na prod. som potom v pondelok skusal zatial iba 500 a 404 (obe fungovali)

**Comment by malymichal** [comment]
![screen shot 2015-12-14 at 21 48 55](https://cloud.githubusercontent.com/assets/6077493/11897599/3b0f9944-a591-11e5-9d72-1494f67f3cd9.png)

**Comment by martinmacko47** [comment]
Skus vyrobit CSRF incident: Chod na stranku s formularom, pomocou developer tools v browsri umaz z formularu hidden field s CSRF tokenom, a potom submitni.

**Comment by malymichal** [comment]
ano, robi to presne to, co poslal user. 
![screen shot 2015-12-18 at 14 28 51](https://cloud.githubusercontent.com/assets/6077493/11897896/bcdb5a6a-a593-11e5-8969-e19e759687b8.png)

**Comment by martinmacko47** [comment]
Okej, tak nieco nefunguje. Vraciam spat do stavu new a niekedy sa na to pozriem. Ostatne chybove stranky vyzeraju ze funguju, takze nechame ich deploynute.

**Comment by martinmacko47** [comment]
Template pri CSRF chybe je natvrdo zadrotovany v kode Djanga. Obsahuje zopar vysvetlujucich textov podla toho, co zlyhalo, ktore by som musel natvrdo opisat, keby som chcel spravit vlastny template. Kaslem na to, tuto chybu by bezny user vidiet aj tak nemal.
