### ISSUE TITLE
logout 1 step

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#91]
Jednokrokovy logout nefunguje -- ked kliknem Odhlasit, tak sa ma este pyta, ci ozaj odhlasit.

**Comment by mmmaly** [comment]
(nie je kriticka feature, ale mozno suvisi s JS haluzami)

**Comment by martinmacko47** [comment]
Pls, otestuj, ci pomohlo. Mal by fungovat aj autocomplete institucii.

**Comment by mmmaly** [comment]
pomohlo.
