### ISSUE TITLE
kluce pre prod - socialne siete

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#92]
Fb je dev kluc: Treba dat realnu adresu a vyklikat to v dev.fb rozhrani.
Ostatne siete: Skontrolovat, a updatnut callbackove url, ak treba.

**Comment by martinmacko47** [comment]
Ked ideme pozyvat ludi, asi by bolo fajn, aby kluce fungovali.

**Comment by mmmaly** [comment]
- [x] facebook
- [x] google
- [x] twitter
- [x] linkedin

**Comment by mmmaly** [comment]
facebook som vytvoril produkcny kluc, zvysne su ok

**Comment by mmmaly** [comment]
a teda vyskusane aj prepojit, aj prihlasit

**Comment by martinmacko47** [comment]
Pls, premenuj FB kluc nejak, nech je jasne, ze ten je ten oficialny. Lebo mame tam asi 4 rozne kluce. Nech ho omylom neumazeme.
