### ISSUE TITLE
implement HSTS

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#93]
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by mmmaly** [comment]
Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"

set.

**Comment by martinmacko47** [comment]
Btw, mozno by sme mohli domenu submitnut sem: https://hstspreload.appspot.com/
(po overeni, ze to nie je nejaky scam) Ak myslis, ze je to blbost, tak kasli na to a issue zatvor. Zatial reopenujem.

**Comment by mmmaly** [comment]
submitnute, 
este mi to odporucilo precheckovat nastavenia, https://www.ssllabs.com/ssltest/analyze.html?d=chcemvediet.sk
Dokopal som to k A+ (povodne C).
