### ISSUE TITLE
configure LimitRequestBody

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#94]
obmedzit velkost uploadovanych suborov a aj otestovat, ake velke prilohy vlastne vieme uploadnut.
https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody

**Comment by mmmaly** [comment]
nastavene, na taku velkost, aby vedeli este uploadovat rozumne velke prilohy (20MiB)
