### ISSUE TITLE
requesty priamo na IP

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#97]
```
[2015-12-02 09:12:24,318] django.security.DisallowedHost ERROR Invalid HTTP_HOST header: '46.229.232.131'. You may need to add u'46.229.232.131' to ALLOWED_HOSTS.
[2015-12-02 09:22:20,116] django.security.DisallowedHost ERROR Invalid HTTP_HOST header: '46.229.232.131'. You may need to add u'46.229.232.131' to ALLOWED_HOSTS.
```

Odkial k nam idu requesty priamo na IP? Bud ich povolit, alebo zakazat uplne. Ja som za zakazat. Tj. vo vhost apachovi nastavit, nech pusti len danu domenu a nic ine.

**Comment by mmmaly** [comment]
nejake internetove scannery (74.82.47.3 scan-10.shadowserver.org a podobne).

**Comment by martinmacko47** [comment]
imho priamo na IP by nic byt nemalo: zbytocne si znizujeme google rating, ze mame na dvoch zdrojoch rovnaky obsah.

**Comment by mmmaly** [comment]
ServerName je nastavene, neviem, ci to pomoze.

**Comment by martinmacko47** [comment]
mam pocit, ze ak je znama iba IP tak sa zoberie prvy vhost v poradi. Takze ak spravis nieco taketo: http://serverfault.com/questions/583884/apache-listen-only-on-specific-domain-not-ip#answer-583885
tak bez zadania domeny by to malo poslat 403. Potrebujes to zrejme spravit pre oba porty.

**Comment by mmmaly** [comment]
ok, default nastaveny na redirect, uvidime, co to povie v logoch.

**Comment by martinmacko47** [comment]
Ked sa zada rucne url https://46.229.232.131/ tak (ocakavatelne) hodi chybu "This Connection is Untrusted". To nie je dobre. Radsej zakazat connection, nez hadzat chyby imho.

**Comment by mmmaly** [comment]
Uf, rozmyslam, ci toto sa vobec da, pokial sa nepouziva SNI: Akonahle sa uz urobi connection na 443, bez SNI sa zacina uz cely kolotoc s certifikatmi, a vtedy je uz neskoro.

Vid napr. Websupport:
https://195.210.29.66
alebo G:
https://64.15.113.153/

**Comment by martinmacko47** [comment]
Aha, ok. Tak potom to nechcajme tak. Redirekty funguju.
