### ISSUE TITLE
test.chv.sk by malo byt za htaccess, alebo vypnute

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#99]
nech nemame na dvoch url rovnaky obsah. Aktualne ak napises http://test.chcemvediet.sk/ tak to redirectne na https://www.chcemvediet.sk/, ale ak napises http*s*://test.chcemvediet.sk/ tak to vyhodi ssl warning a potom normalne pusti na stranku.

**Comment by mmmaly** [comment]
ok, vypnute (DNS), zmeny sa prejavia do x hodin.
